### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by josephg** [reactsydney/talks#1]
I've been playing around with graphql a bunch over the past few weeks. I'd love to give a talk introducing graphql at some point!

**Comment by jesstelford** [comment]
Definitely a relevant topic to the React ecosystem these days.

Have a stab at filling out the details so we can get others excited about it too :)

* Talk Date
* Talk Title
* Length
* Twitter-sized Overview (140 characters)
* Detailed Overview

PS: Great to see you might be able to make it!

**Comment by jesstelford** [comment]
@josephg Still keen to give a talk? We have a spot for the November 9th meetup if you're able to put the talk together before then?

**Comment by josephg** [comment]
Yeah happy to!

I could either talk about the (crazier) stuff I've been doing with graphql or just give a general introduction to it - what do you think? Either way probably half an hour-ish would be best.

**Comment by jesstelford** [comment]
A half hour talk would be excellent :)

We're running a poll to see what the general level of folks in Sydney is at, but I would say you can't go wrong with giving an introduction to how graphql works, then follow on with some examples of the crazier use cases, etc, possibly linking to a github repo / blog post for more details if anyone wants to continue learning.

**Comment by josephg** [comment]
Sounds good. I'll put something together!

**Comment by jesstelford** [comment]
@josephg How's prep going?

Do you mind filling out some info so we can announce the talks:

* Talk Title
* Length
* Twitter-sized Overview (140 characters)
* Detailed Overview

**Comment by josephg** [comment]
Sure! Sorry, I've been procrastinating about thinking about how I'm designing the talk. I want to mostly give an introduction to graphql and hold back the crazy stuff until later.

- **Title:** One query per page: React with GraphQL
- **Length:** 30 minutes
- **Overview:** When we're building web apps we can do much better than REST as a data transport. I'll be showing off GraphQL - what it is, why its sexy and some hints of where this wonderful road will take us over the next few years.
- **Twitter version:** GraphQL - what it is, why its sexy and some hints of where it'll take us over the next few years.

**Comment by jesstelford** [comment]
Thanks mate :)

**Comment by jesstelford** [comment]
The video is now online: [One query per page: React with GraphQL ](https://www.youtube.com/watch?v=LdZQzgy9NCI&list=PL_f9f1oPmaTz55pvL3mjxqDsIVEasxl9s&index=4)

You can view all talks from this event [here](https://www.youtube.com/playlist?list=PL_f9f1oPmaTz55pvL3mjxqDsIVEasxl9s).

**Comment by josephg** [comment]
:D:D

Thats a much better perspective than mine:

![screen shot 2015-11-11 at 12 33 06 pm](https://cloud.githubusercontent.com/assets/47413/11081399/69a034a0-8870-11e5-85fc-8d6c292da2a7.png)

**Comment by jesstelford** [comment]
Haha, if you stand still for long enough, you can read the text off your shirt :P
