### ISSUE TITLE
Tackling the Big3 in design systems.

### ISSUE THREAD

**Issue by tuan23** [reactsydney/talks#100]
## Talk Date
July Meetup

## Talk Title
Tackling the Big3 (Colour. Type. Space.) in design systems.

## Twitter-sized Overview (140 characters)
Our approach to tackle the Big3 when designing and building a design system.

## Detailed Overview
A design system must consider many different aspects and solve for many different use cases. The fundamental building blocks which make up any design system are the Big3 (Colour. Type. Space.). In this talk, we share our unique and effective approach to defining the Big3 and carrying those definitions through to the products we build.

**Comment by jesstelford** [comment]
<3 it! This will be a great talk 🎉
