### ISSUE TITLE
MDX || Markdown to MarkDAMN

### ISSUE THREAD

**Issue by tomWritesCode** [reactsydney/talks#101]
## Talk Date
August

## Talk Title
MDX || Markdown to MarkDAMN!

## Length
20 Minutes

## Twitter-sized Overview (140 characters)
MDX brings the world of components to the convenience of Markdown.

The ability to blend JSX with Markdown you have the ability to pull components straight into your markdown file.

Turning a Markdown file into an interactive project opens up a world of possibilities.
## Detailed Overview

Markdown is a fantastic format for writing long-form easily and quickly. MDX brings the same ease and convenience to the component era. Being able to embed JSX straight into a Markdown file, as well as import interactive components. MDX blends the best of Markdown with componentization to unlock a new world of potential.

**Comment by jesstelford** [comment]
This is going to be a great talk! Scheduled in for our next event on August 5th.
