### ISSUE TITLE
Custom hooks made form validation simple

### ISSUE THREAD

**Issue by bluebill1049** [reactsydney/talks#102]
## Talk Date
September 2nd

## Talk Title
React Hook Form

## Length
30min + questions

## Twitter-sized Overview (140 characters)
Talking about the history of form building and introducing a new react hooks library for building form uncontrolled.

## Detailed Overview
Right now our industry is dominated with building form controlled, and I want to give an equal opportunity to build forms uncontrolled with custom hooks, and showing it can be potentially much easier and flexible to build with the library.

**Comment by jesstelford** [comment]
Love it! Thanks for the submission (and the library) Bill! Let's schedule this in for our September 2nd event 👍

**Comment by bluebill1049** [comment]
Sounds great, thanks @jesstelford I will start to prepare my talk ❤️

**Comment by bluebill1049** [comment]
Hi @jesstelford , wondering if the meetup still happen next week?
