### ISSUE TITLE
Redux Observable vs Redux Saga vs Redux Thunk vs MobX State Tree

### ISSUE THREAD

**Issue by fwouts** [reactsydney/talks#103]
## Talk Date
7 October 2019

## Talk Title
Redux Observable vs Redux Saga vs Redux Thunk vs MobX State Tree

## Length
1 hour (can have more audience participation if it's longer)

## Twitter-sized Overview (140 characters)
What does it look like to implement the same feature with the most popular React state management frameworks? Let's live code it together.

## Detailed Overview

As part of rearchitecting the web frontend's codebase at Airtasker, we took the time to build a series of React prototypes to evaluate different state management frameworks. They're functionally identical and re-implement a small part of Airtasker. They share the same code wherever possible (e.g. services and design components), all implement server-side rendering and use TypeScript for type safety.

In order to get a feel of each framework, we'll live-code a small additional feature on top of each prototype.

**Comment by jesstelford** [comment]
This sounds like a great talk!

An hour is quite long to keep everyone engaged in the talk - you mentioned audience participation, how do you imagine that taking place?

**Comment by fwouts** [comment]
Things I'd imagine asking the room:
- what Redux actions would you need to declare
- making some intentional mistakes and asking the room to help debug (e.g. forgetting to add reducers to configureStore())
- asking people to explain what is a thunk

It could also be shortened to just Redux Thunk vs MobX State Tree, with just a quick mention of the two others :)
