### ISSUE TITLE
Test Driven Development with React

### ISSUE THREAD

**Issue by lionbee** [reactsydney/talks#104]
## Talk Date
04 November 2019

## Talk Title
Test Driven Development with React

## Length
30min (max)

## Twitter-sized Overview (140 characters)
Test Driven Development emphasises quick iterations for your code. You won't code faster, but perhaps you will be more accurate.

## Detailed Overview
TDD has been around for a while and I have avoided it for most of my career. I decided for the month of October all code I write I will do TDD. The result was much more positive than I thought it would be and made me rethink how I code.

This talk covers the testing pyramid, the importance of unit testing and the tools I use for testing React. As part of the talk I will work through a trivial example to demonstrate how to do TDD.

**Comment by jesstelford** [comment]
Hey @lionbee, this is an excellent topic! I'd love to have you give this talk at our December 2nd event if you're available?

**Comment by lionbee** [comment]
I'll make myself available @jesstelford 😁

With the move away from Meetup, is this still where to submit talks?

**Comment by jesstelford** [comment]
🎉

I've actually just opened CFP submissions on Cete. It'd be great if you could submit your talk there; https://beta.cete.io/react-sydney, that way I can manage it along side the others coming in 👍

**Comment by lionbee** [comment]
Perfect, will close this issue
