### ISSUE TITLE
Control statements and other React impossibilities with Babel plugins

### ISSUE THREAD

**Issue by AlexGilleran** [reactsydney/talks#11]
**Talk Date**
Whenever the next one is? April?

**Talk Title**
Control statements and other React impossibilities with Babel plugins

**Length**
15 - 30 minutes, depending on how much time there is? I can go into more or less detail, I think the ideal would be 20 minutes or so.

**Twitter-sized Overview (140 characters)**
How to make Babel plugins that extend what React is normally capable of, like  [add if and for statements](http://github.com/AlexGilleran/jsx-control-statements), [automatically apply styles](https://github.com/pwmckenna/react-transform-style) or [highlight updated components](https://github.com/spredfast/react-transform-render-visualizer).

**Detailed Overview**
The necessity of compiling JSX has had the unexpected advantage that nearly every React dev is running Babel 6, which is not just an ES6 transpiler but also a powerful macro system that allows you write code that wouldn't normally be possible.

Ideally this should open everyone's eyes to the possibilities (and dangers) of manipulating the code that they write during transpilation, as well as giving a brief explanation of how to do it. It'll also use [jsx control statements](http://github.com/AlexGilleran/jsx-control-statements) as an example, seeing how I'm familiar with how that works and I'd like to plug it :).

- Introduction and brief history of transpilation in React, leading into...
- ... an explanation of why Babel 6 is exciting not just for compiling ES6 and JSX, but also how it's evolved into a general macro-esque system for Javascript.
- High-level overview of how Babel works
- Lower-level example of how to write a really basic Babel plugin that does something silly like change every comment into an `alert`
- Quick look at the [Babel React Transform](https://github.com/gaearon/babel-plugin-react-transform) and the fun you can have with that
- Lower-level look at how you can manipulate JSX itself
- Case study of [JSX Control Statements](http://github.com/AlexGilleran/jsx-control-statements), how it works, how it's tested etc.
- Mention of the dangers involved, and the (high) potential of blowing your foot off if you get carried away
- Conclusions, (probably including a brief back-in-my-day whinge about the pace of Babel development, how I had to figure out all this by reading source code but now you can read https://github.com/thejameskyle/babel-handbook and it's much easier)
- Questions / Comments / People telling me if statements don't belong in React and I'm a heretic.

**Comment by jesstelford** [comment]
Excellent proposal @AlexGilleran! Let's get you into the next meetup with a 20 minute slot + some Q&A.

The next one is scheduled for April 4th.

**Comment by AlexGilleran** [comment]
Great :)

**Comment by jesstelford** [comment]
@AlexGilleran We'll have you give the closing talk for the night (after our super secret special guest's lightning talk). Depending on the run times for the previous talks, this will be around 7:45.

**Comment by jesstelford** [comment]
@alexgilleran Excellent talk tonight! Thanks so much!

Do you mind if we upload the recording of your talk to YouTube? If so; any links or resources to add to the description?

**Comment by jesstelford** [comment]
Oh, and do you mind sharing a link to your slides here?

**Comment by AlexGilleran** [comment]
Sure, definitely happy to have it on YouTube :)

Slides are here: http://alexgilleran.github.io/babel-plugins-talk/

Resources in the talk: 
- https://github.com/AlexGilleran/jsx-control-statements
- https://github.com/thejameskyle/babel-handbook
- http://astexplorer.net/
- https://github.com/estree/estree
- https://github.com/facebook/jsx/blob/master/AST.md
- https://github.com/ooflorent/babel-plugin-graphql
- https://github.com/danmartinez101/babel-preset-react-hmre
- http://thedailywtf.com/articles/We-Use-BobX
- https://github.com/gaearon/babel-plugin-react-transform
- https://github.com/spredfast/react-transform-render-visualizer
- http://www.meetup.com/rhok-sydney
