### ISSUE TITLE
Publish isomorphic + static gen websites with React

### ISSUE THREAD

**Issue by bguiz** [reactsydney/talks#12]
**Talk Date**
May

**Talk Title**

Publish isomorphic + static gen websites with React

**Length**

15mins

**Twitter-sized Overview (140 characters)**

Git push -> React -> TravisCI -> Github Pages

**Detailed Overview**

React can render to both in-browser, as well as a to a string. The latter is usually used for isomorphic websites. Thanks to [markdalgleish/static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin) doing the heavy lifting, and a few node modules of my own, it can now also be used as a static site generator.

I have switched from using [docpad](https://github.com/docpad/docpad) to this webpack+react solution for [my own blog](http://blog.bguiz.com), and managed to cut the build times down by an order of magnitude.

... but wait, there's more! Since React renders on both the client and the server, the static site can (optionally) and let React "take over" in the browser, and become a Javascript app, where you can navigate between one page and another without refreshing the page, making for a very snappy experience.

Things I'll talk about:

- webpack + [markdalgleish/static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin)
- [reactjs/react-router](https://github.com/reactjs/react-router)
- [nfl/react-helmet](https://github.com/nfl/react-helmet)
- [bguiz/find-posts](https://github.com/bguiz/find-posts)
- [bguiz/reactpub](https://github.com/bguiz/reactpub)
- [bguiz/autodocs](https://github.com/bguiz/autodocs)

**Comment by jesstelford** [comment]
Excellent topic! We'd love to have you present at our next meetup on May 2nd :)

**Comment by bguiz** [comment]
Sounds like a plan!


W: http://bguiz.com

**Comment by jesstelford** [comment]
@bguiz We'll get your talk up first - around 6:30, followed by pizza!

Looking forward to it :)

**Comment by jesstelford** [comment]
@bguiz Here are a couple of pro tips:

* If you have code examples; make them take up the entire screen - our displays are 2 x flatscreen TVs; we want to ensure the folks at the back are able to see the code also.
* We have a hand-held mic (no lapel mic unfortunately), so prepare for that
* Think about where you need your laptop positioned for advancing slides (at the front of the room, or off to the side)

**Comment by bguiz** [comment]
Thanks for hosting @jesstelford !

As promised last night, here are the links for the presentation:

- [blog post](http://blog.bguiz.com/2016/publish-websites-using-reactjs/)
- [slides](http://blog.bguiz.com/presentations/publish-websites-reactjs/)

Since many of the slides are just pictures, the speaker notes in the source for the presentation could be handy:

- [speaker notes](http://blog.bguiz.com/presentations/publish-websites-reactjs/index.md)
