### ISSUE TITLE
Performance optimisations for React applications

### ISSUE THREAD

**Issue by alexreardon** [reactsydney/talks#13]
**Talk Date**
June

**Talk Title**
Performance optimisations for React applications

**Length**
20 minutes + Q&A

**Twitter-sized Overview (140 characters)**
Performance optimisations for React applications

**Detailed Overview**
I will go through:
- tools you can use to find performance problems in your application
- main performance optimisations you can use in your application

I gave a [lightning talk version of this content at sydjs](https://www.youtube.com/watch?v=hbCwF3QVr7o)
This talk would be a more detailed version of it

I also have written [a blog post on the topic](https://medium.com/@alexandereardon/performance-optimisations-for-react-applications-b453c597b191#.9i8kutgex)

**Comment by jesstelford** [comment]
This is an excellent topic! I've been very interested by Paul Irish's [m.reddit.com performance audit](https://github.com/reddit/reddit-mobile/issues/247), and the other recent one [of m.imgur.com](https://github.com/perfs/audits/issues/1).

We'd love to have this talk at our May 2nd meetup, thanks so much for submitting it!

**Comment by jesstelford** [comment]
@alexreardon Are you still able to give this talk on May 2nd?

**Comment by alexreardon** [comment]
Could I move this to June? I did not realise it would be so early in May.

**Comment by jesstelford** [comment]
Yeah, not a problem at all :)

It'll be on Monday June 6th.

**Comment by alexreardon** [comment]
It looks like that the date conflicts with [CampJS](http://lanyrd.com/2016/campjsnews/) (even if only slightly)

**Comment by jesstelford** [comment]
Ah, good point. From past experiences, the last day of CampJS is cleanup / shipout by midday - do you know if that's still the case here?

@DamonOehlman what's the schedule look like on the 6th?

Unfortunately we've already locked the date in, but there are many more future opportunities. If you'd prefer July, it's on the 4th.

**Comment by DamonOehlman** [comment]
@jesstelford Yep, Monday is definitely just a cleanup and shipout affair.  Ferries out at 8am and 10am IIRC, so shouldn't be any real conflicts.  People should book in for React Sydney as a way to let themselves down gently :)

Also, LMK if you want me to set you up a discount code for distribution at your May event.

**Comment by jesstelford** [comment]
Thanks @DamonOehlman - we'd definitely be interested in sharing a code for CampJS :)

@alexreardon Given CampJS wraps up early Monday, did you want to talk on Monday night of June 6th? (Entirely up to you)

**Comment by jesstelford** [comment]
@alexreardon Would July 4th work better for you? We should have enough talks for June if you want to get some R&R after CampJS and wait till next month?

**Comment by alexreardon** [comment]
Yeah that works for me @jesstelford

**Comment by jesstelford** [comment]
Hey @alexreardon, still keen to talk on July 4th (this Monday)?

**Comment by alexreardon** [comment]
Yep

**Comment by jesstelford** [comment]
Awesome - we've got you locked in for the final talk of the night, at around 8:00 - 8:15pm. Thanks!

**Comment by alexreardon** [comment]
I had a great time. Cheers!
I will submit an issue for the next talk once I know what I will say!

**Comment by lyntco** [comment]
https://youtu.be/TsAIo05s0DQ

**Comment by jesstelford** [comment]
Wow, thanks for all the recordings @lyntco! They're excellent!

**Comment by alexreardon** [comment]
I had a great time. Cheers @jesstelford
