### ISSUE TITLE
Strategies for Scaling Your Dev Team

### ISSUE THREAD

**Issue by martinli11** [reactsydney/talks#14]
**Talk Date**
May

**Talk Title**
Hiring Strategies and Best Practices To Scale Your React Team

**Length**
15mins

**Twitter-sized Overview (140 characters)**
Global Trends/Data -> React Trends/Data -> React in Australia -> Best Practices

**Detailed Overview**
One candidate gets his/her dream job on the Hired platform every three hours. What has Hired seen in terms of data across the globe for React developers? What are the trends developing for React developers globally and in Australia?

In today's competitive hiring environment, what are some best practices and strategies to get the most out of your teams? What is the key to hiring well, and hiring fast so you can be first to go to market with your product?

Speaker will be Sascha Gray, Head of ANZ for Hired.

More info on Hired: http://bit.ly/1UXYM3k

**Comment by jesstelford** [comment]
@martinli11 Thanks for submitting the proposal.

It's an interesting topic, in particular the job trends in Australia related to React.

We're happy to have Sascha present at the meetup, however we want to make sure it isn't a sales pitch for Hired, and in particular we want to make sure it isn't a recruiting pitch to find candidates to sign up to Hired.

For example, what we'd prefer to avoid (very condensed):

> Hired is great. React is growing [insert stats]. Sign up for Hired and we can help you get a React based job.

The way we'd prefer it to be presented:

> React is growing. Here is a bunch of interesting information on React + hiring, proving that it's growing. At hired, we're tracking all this interesting information.

If that's doable, then we'd love to have Sascha give the talk.

**Comment by martinli11** [comment]
@jesstelford 

Thanks for the feedback, what you proposed is definitely in line with what we are thinking.

What date did you have in mind for the talk?

**Comment by jesstelford** [comment]
Excellent to hear :)

May 2nd is the next meetup, does that work for Sascha?

**Comment by martinli11** [comment]
When is the next meetup after the 2nd? Might be a bit tight given she is back early next week.

**Comment by jesstelford** [comment]
No worries, June 6th is the next one (First monday of every month)

**Comment by martinli11** [comment]
That works for us, looking forward to it!

**Comment by martinli11** [comment]
@jesstelford - just wanted to check whether we are confirmed for June 6th? We are good to go :)

**Comment by jesstelford** [comment]
@martinli11 June 6 is confirmed :)

Thanks for putting the talk together - it'll be really interesting.

**Comment by jesstelford** [comment]
@martinli11 We'll have Sascha up as the first speaker on Monday, around 6:30.

**Comment by martinli11** [comment]
Sounds good, thanks @jesstelford
