### ISSUE TITLE
Beyond React: Functional Programming with Elm

### ISSUE THREAD

**Issue by damienklinnert** [reactsydney/talks#15]
**Talk Date**
The May meetup probably, is the date already announced?

**Talk Title**
Beyond React: Functional Programming with Elm

**Length**
30 mins

**Twitter-sized Overview (140 characters)**
Do you love React, Redux and JS? Then you should definitely learn about Elm, a functional language, for the browser, focussed on usability!

**Detailed Overview**
Do you love React, Redux and JS? Then you should definitely learn about Elm.

Elm is a functional programming language made especially for the browser, with a clear focus on usability. It follows the same principles as React and Redux, but offers you way more:
  
- no runtime exceptions, ever! if it compiles, it will run!
- super fast rendering thanks to a virtual Dom 
- hot code reload and a time travelling debugger that work out of the box
- a package manager that makes update a snap by enforcing semver
- an amazingly open, friendly and helpful community

Damien has started to use Elm in his side projects and instantly fell in love with it. He'd like to give you a first impression of the language and show you were to get started. 

Bonus: the word monad is not even mentioned a single time in the core libraries!

**Comment by jesstelford** [comment]
I'd personally love to see this talk, and it's a great match for the folks attending React Sydney!

Right now it looks like we're full for our May meetup, but did you want to present at the June one? (June 6th)

**Comment by mordrax** [comment]
The other three talks are only 15-20mins, would love to attend for this one, by far the most interesting topic to me :)

**Comment by halhenke** [comment]
![](http://i.giphy.com/qVg8lJSwPNros.gif)

**Comment by nkbt** [comment]
Elm is great, :+1:

**Comment by jesstelford** [comment]
The community has spoken!

@damienklinnert Would you like to give this talk at our May 2nd meetup?

**Comment by damienklinnert** [comment]
Hey,
Thanks for all the interest in this!
I'd love to give the talk this Monday. Unfortunately I'm at Lambda Jam in Brisbane right now and won't be able to make it until Monday. Sorry for the confusion - my bad.

June, 6th would work perfectly for me! What do you think?

Cheers
 Damien

**Comment by halhenke** [comment]
...Are there enough talks now. I understand the others are shorter?

**Comment by halhenke** [comment]
At any rate - if you need it I think i could throw together a quick talk this weekend. Recently gave a talk on RxJS/Observables (in which i said there wasnt much interesting going on recently in the React/Redux landscape) and am now pretty interested in [mobx](https://github.com/mobxjs/mobx) which just sort of popped up.

Could do a quick Observable intro/brush up and then compare it to redux? I know my last talk kind of sucked but **THIS ONE WOULD BE BETTER**....maybe ;-)

Anyway - if things are otherwise fine time-wise dont worry about it.

**Comment by halhenke** [comment]
@jesstelford Dont mind either way - but _if_ this would help, let me know before tomorow.

Otherwise we can always have @JedWatson talk again :-)

(Actually maybe not - forgot about the Dad thing)

**Comment by jesstelford** [comment]
@halhenke Yeah, we'd love to have you back. The first talk was great! Open a new Issue with the standard info, and we'll put you in on Monday.

**Comment by jesstelford** [comment]
@damienklinnert Not a problem! The next one is June 6th :)

**Comment by halhenke** [comment]
@jesstelford Will open the new issue later tonight 👍

**Comment by mordrax** [comment]
With the departure of signals and introduction of subscriptions in Elm 0.17, I hope that there's enough time to update the talk to include all the new things coming up in 0.17.

**Comment by jesstelford** [comment]
@damienklinnert Still ok for June 6th? We'd love to see this talk; the community is clearly excited about it!

**Comment by damienklinnert** [comment]
@jesstelford yep definitely :)

**Comment by jesstelford** [comment]
@damienklinnert We'll have you up as the third ("keynote") speaker on Monday. Around 7:50 - 8pm.s

**Comment by damienklinnert** [comment]
Awesome! Excited about that!
