### ISSUE TITLE
Observables & Reactive Programming in RxJS & MobX

### ISSUE THREAD

**Issue by halhenke** [reactsydney/talks#16]
## Talk Date
Tomorrow
## Talk Title
Observables & Reactive Programming in RxJS & MobX
## Length
30 to 45 mins
## Twitter-sized Overview
Will explore RxJS & the concept of Observables. Then a look at how MobX uses the same ideas to deal with state management in React Apps.
## Detailed Overview

**Comment by jesstelford** [comment]
Awesome submission!

We'll have you up second. Around 7:15pm.

Look forward to hearing your talk :)

**Comment by jesstelford** [comment]
Here are a couple of pro tips as a reminder:

* If you have code examples; make them take up the entire screen - our displays are 2 x flatscreen TVs; we want to ensure the folks at the back are able to see the code also.
* We have a hand-held mic (no lapel mic unfortunately), so prepare for that, and be conscious of talking directly into the microphone.
* Think about where you need your laptop positioned for advancing slides (at the front of the room, or off to the side)

**Comment by jesstelford** [comment]
Thanks again Hal - great talk as always :)
