### ISSUE TITLE
Universal rendering of animated responsive layout

### ISSUE THREAD

**Issue by nkbt** [reactsydney/talks#19]
## Talk Date
06.06.2016

## Talk Title
Universal rendering of animated responsive layout

## Length
20-30min

## Twitter-sized Overview (140 characters)
Solving a universal rendering puzzle of animated responsive layout without global styles and media queries.

## Detailed Overview
React wants you to have exactly the same server output as you will get rendered in the browser. Which is reasonable and not React-specific. That is usually not a big deal and can be quickly fixed.

Though when it comes to a responsive design, JS styles (or css-modules), ui-routing, ui-animations (and you don't want to use media queries) - you end up with a fancy puzzle that initially feels totally unsolvable. Server, basically, does not have your screen dimensions to make correct UI rendering.

We've spent some time cracking the problem and this is what I am going to talk about. The solution is obviously quite opinionated in terms of tech stack and requirements, but should be helpful in finding your own way. I'll try to stay very high level and focus on conceptual solution, rather then on a specific tech.

#### PS: why not media quieries?
1. Since they are basically a hack and break concept of modularity, and Element Queries are not there yet ([read here](http://ianstormtaylor.com/media-queries-are-a-hack/), [here](http://www.sitepoint.com/beyond-media-queries-time-get-elemental/) or even [here](https://www.smashingmagazine.com/2013/06/media-queries-are-not-the-answer-element-query-polyfill/))
2. They cannot be really connected to UI routing

**Comment by jesstelford** [comment]
An excellent topic! Locked in for June 6th.

**Comment by jesstelford** [comment]
@nkbt We'll have you up as the second speaker on Monday, after pizza, around 7 - 7:15.

**Comment by nkbt** [comment]
Cool, thanks.

Just realized that it is going to be quite tough since we don't have a large screen and most of things I was going to show - code and demos. It' a bit too technical to create 1-2 line slides...

I'll try to figure out how to present it with our limitations.

See you on CampJS 👋

**Comment by nkbt** [comment]
Related links: 

Demo project (the one I ran in every iframe) https://github.com/nkbt/un-responsive-demo

Slides: https://github.com/nkbt/un-responsive

Why not media queries (just an example article, there are other ones around pretty much same idea):
http://ianstormtaylor.com/media-queries-are-a-hack/

Nice one about react-motion (and fairly fresh)
https://medium.com/@nashvail/a-gentle-introduction-to-react-motion-dc50dd9f2459#.bvuujc3gg

**Comment by martin-jujou-sirca** [comment]
Thanks !

**Comment by halhenke** [comment]
Awesome!
