### ISSUE TITLE
React Start for Dummies

### ISSUE THREAD

**Issue by ButenkoT** [reactsydney/talks#2]
**Talk Date**
9 Nov 2015/ or next meet-up

**Talk Title**
React Start for Dummies

**Length**
30 - 40 mins

**Twitter-sized Overview (140 characters)**
Start react project from a scratch

**Detailed Overview**
Build React project from a scratch with webpack, babel, loaders, tests. Quick walk through package.json, webpack.config.js, unit-tests (tape), end-to-end ui-tests (nightwatch).

**Comment by jesstelford** [comment]
@ButenkoT This will be a great talk to have at the November 9th meetup!

It's only 1 short week away, though - is that enough time for you to put together the complete presentation? We'll have a projector setup for you to connect to.

Thanks so much for submitting the proposal, it's going to be a great night!

**Comment by ButenkoT** [comment]
Glad to hear that. Yes, I ll complete presentation for 9th. Quite the
excited and nervouse about it.

**Comment by jesstelford** [comment]
We're excited too! It'll be great :)

Will you be live-coding on the stage? Ie; will you need both hands free from holding a mic?

**Comment by ButenkoT** [comment]
Yep, will do live-coding, so would be good to have a headset

**Comment by jesstelford** [comment]
Alright, we'll see what we've got available. Might end up being a mic stand instead of a headset, but it's the same end result :)

**Comment by nkbt** [comment]
I think it is a good idea to post links/videos/photos in comments here.

**Comment by jesstelford** [comment]
The video is now online: [React Start for Dummies](https://www.youtube.com/watch?v=hWiV--KqYAo&list=PL_f9f1oPmaTz55pvL3mjxqDsIVEasxl9s&index=2)

You can view all talks from this event [here](https://www.youtube.com/playlist?list=PL_f9f1oPmaTz55pvL3mjxqDsIVEasxl9s).

**Comment by ButenkoT** [comment]
Thanks Jess :)
