### ISSUE TITLE
Let me sell you on redux saga

### ISSUE THREAD

**Issue by MadRabbit** [reactsydney/talks#21]
## Talk Date
next meetup?

## Talk Title
Let me sell you on redux saga

## Length
20-30 mins

## Twitter-sized Overview (140 characters)
Remember how redux made state management so much better in react? Well, redux saga makes side effects management equally awesome.

## Detailed Overview
I'm not sure if you already had a talk about redux saga at the meetup, but if you didn't I could come over and talk about it. I worked on a good dozen of react apps through the last years, and redux is obviously one of the best things that happened to the field. Unfortunately, even though redux had thunks to deal with async processing, side effects management was less than stellar. Redux saga fills in this gap and makes async tasks manageable, testable and combinable in the same way as redux made the app state manageable, testable and combinable. And I can explain why.

**Comment by halhenke** [comment]
Sounds great!

![](http://media.riffsy.com/images/77d692c24e3e97a0bd67a182af4bc211/raw)

**Comment by jesstelford** [comment]
@madrabbit This will be a great talk for our next meetup on July 4th (this Monday)!

Once you've confirmed, we'll sort out the run order :)

**Comment by MadRabbit** [comment]
Lets do this then! :)

**Comment by jesstelford** [comment]
We'll get you up second, after Pizza's; around 7:20.

**Comment by jgrancher** [comment]
@MadRabbit Is that possible to get the slides somewhere? Couldn't do it on Monday, so I'd love to read about it. 👼

**Comment by MadRabbit** [comment]
@lyntco was actually recording the whole thing. i'm not sure if she ended up publishing it somewhere though

**Comment by subshad** [comment]
@lyntco 's recordings from other meetups usually end up at https://www.youtube.com/channel/UCn7J70PJA8HFoHfeK6fLkGg a couple of days after the event

I'm sure these will as well.

**Comment by lyntco** [comment]
I've been moving this week, should be tonight up if we get internet today!

**Comment by lyntco** [comment]
https://www.youtube.com/watch?v=H4I9EKGTvCE 👍

**Comment by MadRabbit** [comment]
Thanks Lyn!
