### ISSUE TITLE
Live React in ClojureScript

### ISSUE THREAD

**Issue by escherize** [reactsydney/talks#22]
## Live React in ClojureScript

I'm the author of cljsfiddle.com, and I'd like to introduce how we in the Clojure community harness the power of react.  

## Length
20-40 min

## Twitter-sized Overview (140 characters)
Intro to Clojure[Script] and a look at http://cljsfiddle.com

## Detailed Overview
Like http://escherize.com/cljsfiddle_talk but targeted at JavaScript and react users.

**Comment by jesstelford** [comment]
@escherize ooh, this'll be an interesting one :)

You're ok to give the talk on July 4th (this Monday)?

**Comment by escherize** [comment]
Yep!

I will update the talk and be ready to present July 4th!

**Comment by jesstelford** [comment]
We'll have you up first around 6:20, right before pizzas arrive around 7pm :)

**Comment by lyntco** [comment]
https://youtu.be/FDRBTXfFOhw 👍
