### ISSUE TITLE
React & Redux at a global scale

### ISSUE THREAD

**Issue by juliamitchelmore** [reactsydney/talks#23]
## Talk Date
September 12th 2016

## Talk Title
Redux: Try This for Size

## Length
Up to 40 mins

## Twitter-sized Overview (140 characters)
The trendy tale of how a global fashion retailer dressed itself in this season's must-have tech framework: React + Redux

## Detailed Overview
UK-based fashion retailer Arcadia Group (who own Topshop, Topman, Miss Selfridge etc.) recently undertook an ambitious project to pull the websites of their seven brands into the modern age by rebuilding the mobile platform from the ground-up with React and Redux. Along the way, we made many decisions about how to use the technology to best serve a global audience of millions - including ensuring immutability, handling SEO and just how annoying scroll events are! This talk (also to be presented at FullStack Conference 2016 in London) will discuss how we built our app and some of the lessons we learned while doing so.

**Comment by jesstelford** [comment]
Really looking forward to this one :) We've got you down for the 12th of September 👍

**Comment by zer0pants** [comment]
I saw the email call for submissions and this was my first thought too! Loving React w Redux at the moment.

**Comment by jesstelford** [comment]
@juliamitchelmore We'd like to have you as the 2nd speaker of the night on Monday - how goes the planning?

**Comment by juliamitchelmore** [comment]
@jesstelford sounds good to me! few final tweaks to be made, but will be ready to go on Monday. may be slightly jetlagged though haha

**Comment by jesstelford** [comment]
:P The plane is always good for last minute uninterrupted work! What time does your flight get in?

**Comment by jesstelford** [comment]
Thanks again for giving your talk - the jetlag wasn't noticeable at all, I swear! :+1:
