### ISSUE TITLE
Javascript/Node bootcamp for women in Sydney

### ISSUE THREAD

**Issue by ButenkoT** [reactsydney/talks#24]
## Talk Date
1 of August

## Talk Title
How first Sydney NodeGirls went

## Length
10-15mins

## Twitter-sized Overview (140 characters)
on 9th of July we had first NodeGirls coding bootcamp in Sydney. It had great success with 100+ women turn up within whom was around 50% of beginners.

## Detailed Overview
Event had a great success and attracted a lot of newbies to the event, where mentors helped them walk through javascript challenges from nodeschool.io. More experienced women were trying node. Turn out was great and NodeGirls announced on it's launching in Sydney. 
- A quick summary of event feedback and how attract more women to your events, meetups.
- A call for mentors and people who want help to build educational workshops for javascript, react etc

**Comment by jesstelford** [comment]
This is definitely in :) Really great to hear it was a success!

**Comment by ButenkoT** [comment]
Ooops, Jess, is it this Monday? 1st of August? I forgot that Im going on a
premier on 1st of August. I might ask Nik to give an overview instead of me
:(

**Comment by ButenkoT** [comment]
Or I can do it next month. Which would be better? How do you think?

**Comment by jesstelford** [comment]
Yep, Monday August 1st. It'd be good to get an overview of it this month - do you mind if Nik did it?

**Comment by ButenkoT** [comment]
Im totally fine if Nik do it, I just asked him and he is fine with it. I ll
handle him all material, but he have been there as a mentor so he knows
about the things.
Feeling bad aboud this situation, but its ok. Next nodegirls will be in
September.

**Comment by jesstelford** [comment]
Awesome! What date in September for the next one?

**Comment by ButenkoT** [comment]
This one Im confirming with venue (CoderFactory) - 10th or 17th of
September. Will know till the end of this week

**Comment by jesstelford** [comment]
Awesome. The next React Sydney is on Monday the 12th.

**Comment by ButenkoT** [comment]
Cool,
Nik will mention on this Monday that I'm looking for developers who willing
to help with educational modules for JS all levels (but we start with JS
for complete beginners) and Node (same).
But after that I would love to add module on React as well - would be cool.
Cos most of women developers work with Java and Python - would be great to
show them more of cool things and start with complete beginners with
something better then Java :D

Cheers

**Comment by nkbt** [comment]
Slides are up at https://nkbt.github.io/node-girls (keyboard left/right to navigate)

Links:

- [meetup.com / Node-Girls-Sydney](https://www.meetup.com/Node-Girls-Sydney)
- [twitter.com / @NodeGirlsSydney](https://twitter.com/NodeGirlsSydney)
- [twitter.com / #NodeGirlsSydney](https://twitter.com/hashtag/NodeGirlsSydney)
- [facebook.com / NodeGirlsSydney](https://facebook.com/NodeGirlsSydney)
- [discord.gg / RK38uS3](https://discord.gg/RK38uS3)

Any info, help, ideas: tanya@butenko.me

Cheers!
