### ISSUE TITLE
100 ReactJS Components and Counting

### ISSUE THREAD

**Issue by bassjacob** [reactsydney/talks#25]
## Talk Date
August 1st I guess?

## Talk Title
100 ReactJS Components and Counting

## Length
20-30 mins

## Twitter-sized Overview (140 characters)
Maintaining a library of hundreds of components where each is a separate module is a daunting task. Whether you are following either a many-or-mono repository strategy the cognitive overhead can be prohibitive. At Domain.com.au, we have developed a comprehensive set of guidelines and tools around scaling your modular systems to support the magnitude of this approach, including custom build tools, workspaces and rendering strategies.

**Comment by jesstelford** [comment]
Awesome topic!

**Comment by bassjacob** [comment]
Better Belated than never: http://bassjacob.com/presentations/100-components-and-counting

Finally got around to updating my pandoc compiler to handle the md format.
