### ISSUE TITLE
Functional JS

### ISSUE THREAD

**Issue by shineli1984** [reactsydney/talks#26]
## Talk Date
12th Sep

## Talk Title
Functional JS

## Length
60 mins

## Twitter-sized Overview (140 characters)
Functional composition, point free style, Functor, Monad and more...

## Detailed Overview
This talk will go through the basics of functional programming and touch on various concepts like composition, point free style, Functor, Monad and the libs like Ramda and/or bilby. Although this has nothing to do ReactJS particularly, I feel that why not learn to write awesome js to company with a awesome framework like ReactJS.

**Comment by jesstelford** [comment]
Great idea!

For a 60 minute talk, it'd be great if you could tie in some ReactJS specifics, maybe examples of how being functional makes coding in React better with predictable state / more performant renders / etc?

A functional-only talk would be great for a 40 minute time slot if that works better for you?

**Comment by shineli1984** [comment]
@jesstelford Thanks for the suggestion. I can touch on the natural of redux is actually just an event stream Functor. Also, how you can memoize reducers since they are pure function, etc. So to make it more relevant to the group.

**Comment by jesstelford** [comment]
They sound like great suggestions!

How are you tracking for Monday night? We'd like to have you up as our 3rd speaker of the evening.

**Comment by shineli1984** [comment]
Great. I'll be ready for Monday night.

**Comment by jesstelford** [comment]
Really great talk, thanks for giving it! Do you have the slides to share?

**Comment by shineli1984** [comment]
@jesstelford Cheers mate. Thanks for having me.

Here's the video: https://www.youtube.com/watch?v=V4sKhoyB5q8
Here's the slides: https://github.com/shineli1984/react-talk-2016-09-12
