### ISSUE TITLE
Making Beats with React (First time talk)

### ISSUE THREAD

**Issue by simonswiss** [reactsydney/talks#27]
**Talk Date**
12th September 2016

**Talk Title**
Making Beats with React

**Length**
15 - 20 minutes? 

Probably need guidance on that. This would be **my very first meetup talk** so i'd like to keep it short and sweet!

**Twitter-sized Overview (140 characters)**

Demo of the awesome `react-music` recently released by Ken Wheeler. Turn React into a beatmaking machine with an intuitive, declarative API.

( ^ that's 140 characters exactly, for bonus points!)

**Detailed Overview**

I always enjoyed playing music instruments and producing hiphop beats with software like FruityLoops, Reason, Ableton Live.

With life getting busy (kids, work), that hobby slowly faded away in the background.

When Ken Wheeler announced [react-music](https://github.com/FormidableLabs/react-music), I got really excited to join two of my passions - coding and making music. Turns out the API is pretty awesome too, and **makes it really intuitive and fun** to create loops.

I am obviously not the only one excited, since the project already has more than 1k stars on GitHub.

In this talk, I would do a quick introduction to `react-music`, and explore the intuitive API with *live coding examples*. I know... First talk + live coding - what could go wrong? :joy:

However, this is the only way to really demo this properly, and make the talk entertaining / interactive!

The *first time speakers wanted* part is what triggered it for me. 2016 is the year of being pro-active for me, and this would be the next big step.

### Technical Requirements

**To be feasible, this talk would involve 2 things:**

1. A mic stand to have both hands free

2. Audio speakers, for obvious reasons

(3.) A supportive crowd, as this is very much diving in the deep end for me.

If you think it's a good idea and the technical requirements are okay, we can try refine the duration etc. I can also look around for speakers and bring my own desk mic (blue yeti).

**Comment by jesstelford** [comment]
Wooo! :tada:

Locked in for September 12th.

Super excited for your first talk! It's a great, fun topic too :+1:

We're here to help. Let @JedWatson or myself know if there's anything we can do. We've also both got our share of speaking experience, so are happy to impart any tips if you'd like them.

> Mic stand

We're on it! At the least, we can have a human mic stand (aka; I will hold the mic for you ;) )

> Audio speakers

The BlueChilli sound system allows plugging in an external source (which is where our excellent beats come from during the first half hour before the talks start), so we can hook up your laptop that way.

> Supportive crowd

The React Sydney lot are excellent - we've had so much positive feedback about all the attendees it makes everything feel right with the world :D

**Comment by simonswiss** [comment]
Awesome, great answer - thanks!

My only concern at the moment is the length of talk. I think 15 - 20 minutes should be good, but if it needs to be shorter (first time speaker 5min flash talks as they do in SydCSS), I am happy to trim it down!

Ken Wheeler has been pretty supportive too. I never thought my first talk would be at React Sydney, but this seems like a good opportunity to jump in!

And I do 100% agree on the React Sydney crowd being awesome. Hopefully there are other first time speakers to join me on that night!

**Comment by bassjacob** [comment]
Very excited, especially after seeing the youtube video you posted. This should be a great talk!

**Comment by jesstelford** [comment]
15 - 20 minutes is a great length for a first talk!

We'll have you up first on Monday night - how does that sound?

**Comment by simonswiss** [comment]
If there is the possibility to make it a bit longer, I rehearsed a couple of times and the talk would be more around 30 min.. 

I totally understand if that doesn't fit with the evening timing + pizza etc.. so if needed, I can cut down the intro and jump straight to the demos to stick to 20 min.

Going first is fine - may as well get my first public speaking panic mode out of my system and enjoy the rest of the night :)

**Comment by simonswiss** [comment]
Thanks everyone for the great feedback! I had a ton of fun presenting this topic - very stressful to step up in front of everyone, but so glad I did it!

Here is a link to the slides I used during the talk: http://slides.com/simonswiss/react-music

If you wonder where the cool emojis came from - you can have a look at the awesome http://emojione.com

I have also set a live demo of the mixing console here: http://react-music-mix.surge.sh

As a disclaimer, I have only `tested` it in Chrome - it might very well be broken in other browsers / mobile. ¯\_(ツ)_/¯

Finally, you can grab the source code of my demo on https://github.com/simonswiss/react-music which is a fork of Ken Wheeler's project.

Since that repo was prepared for the talk (starts with an empty song shell), you'll need to grab snippets inside `demo/snippets` and paste them inside the `demo/demo.js` to get started.

The mixing console UI is all in one file - so if you grab the file in `demo/snippets/demo3/00_shell.js` and paste it in `demo/demo.js`, the whole thing should start making music for you :)

Thanks again!

**Comment by jesstelford** [comment]
Such a great talk! I wouldn't have known it was your first time if you hadn't told me!

We were honored to have you :)

**Comment by simonswiss** [comment]
Glad you enjoyed it. 

It was a fun topic to present. Really glad I found the courage to submit this talk in the first place - that was probably the hardest part of the process! :)

A big thank you to the ReactSydney community - you guys were very supportive before, during and after the talk! 👍
