### ISSUE TITLE
Performance optimisations for React applications: round 2

### ISSUE THREAD

**Issue by alexreardon** [reactsydney/talks#29]
## Talk Date

Monday December 5th\* will confirm
## Talk Title

Performance optimisations for React: round 2
## Length

20mins + Q&A
## Twitter-sized Overview (140 characters)

In this talk I will explore the performance implications of normalised state and connected components
## Detailed Overview

[In a previous talk](https://github.com/reactsydney/talks/issues/13) I established that we need to be aggressive with `shouldComponentUpdate` in order to have highly performant react applications. My previous talk suggested that denormalising your state was an approach to achieve optimal rendering. However, what if you want to use normalised state? And what about connected components? This talk will dig a little deeper into these options; exploring their performance dangers and opportunities.

**Comment by jesstelford** [comment]
Love it! :+1:

**Comment by jesstelford** [comment]
@alexreardon We've cancelled the October Meetup (falls on a public holiday). Are you able to give this talk at the following one: November 7th?

**Comment by bochen2014** [comment]
yeah,, normalizr is a great tool

actually, I don't think have render() called multi-times is a big concern, as it just render components to the virtual dom. The real dom only gets updated when real change happens.  I believe there is a trade-off here, if it involves too much effort to reduce the render(), i would simply leave with it.
Just my thought though . ;-)

**Comment by alexreardon** [comment]
I am keen to talk on this but I have run out of time to prepare it. Can I push it back to Jan?

**Comment by jesstelford** [comment]
Sure thing - the next meetup isn't until February (January would be the 2nd, which a lot of folks will be away on holiday for).

**Comment by alexreardon** [comment]
I should be good to do this for the Feb meetup @jesstelford

**Comment by jesstelford** [comment]
Excellent! I'll lock it in for Feb 6th 👍

**Comment by alexreardon** [comment]
This one will actually be closer to 30 minutes + Q&A. Lots of ground to cover!

**Comment by alexreardon** [comment]
@jesstelford were the talks recorded last night?

**Comment by jesstelford** [comment]
They were - we're waiting for them to be uploaded, then we'll post the links 👍

**Comment by alexreardon** [comment]
Any update on this one?

**Comment by jesstelford** [comment]
None yet - we're chasing it up, I'm keen to get the videos shared :)

**Comment by alexreardon** [comment]
Okay great

**Comment by jesstelford** [comment]
Video has been uploaded by @anzcoders!

[Performance optimisations for React: round 2 - 34:29](https://www.youtube.com/watch?v=jm81fmVr3co)
