### ISSUE TITLE
Redux: A brief introduction

### ISSUE THREAD

**Issue by gwyneplaine** [reactsydney/talks#3]
**Talk Date**
Monday November 9 , 2015

**Talk Title**
Redux: A brief introduction.

**Length**
10m

**Twitter-sized Overview (140 characters)**
A brief introduction to redux and why you should use it with react. 

**Detailed Overview**
Redux is a predictable state container for javascript applications. 
The talk will be a general overview of how redux works and aims to shed light on its core components, how it applies (and perhaps improves on) "Flux" as an idea. This will all be done in the context of state management in React.

**Comment by jessicace** [comment]
Would really enjoy this!

**Comment by jesstelford** [comment]
The video is now online: [Redux: A Brief Introduction](https://www.youtube.com/watch?v=-9966MwODDU&list=PL_f9f1oPmaTz55pvL3mjxqDsIVEasxl9s&index=3)

You can view all talks from this event [here](https://www.youtube.com/playlist?list=PL_f9f1oPmaTz55pvL3mjxqDsIVEasxl9s).
