### ISSUE TITLE
Physics is beautiful

### ISSUE THREAD

**Issue by alexreardon** [reactsydney/talks#30]
## Talk Date

Monday 7th November
## Talk Title

Physics is beautiful
## Length

20 mins + Q&A
## Twitter-sized Overview (140 characters)

Moving beyond timing based animations to build user interfaces that look and feel beautiful.
## Detailed Overview

Timing based animations get the job done, but they often lack direct relationship to physical objects. This talk will explore some of the tools, techniques, pitfalls, and opportunities faced in building user interfaces with physical properties.

**Comment by jesstelford** [comment]
Love this one - I've been playing about with [cannon.js](https://schteppe.github.io/cannon.js/) a little recently, which is super fun for 3D!

I'm looking forward to this talk :+1:

**Comment by jesstelford** [comment]
Hey @alexreardon All set to go for Monday 7th November's meetup?

**Comment by alexreardon** [comment]
Yep! Good to go

**Comment by jesstelford** [comment]
Loved the live coding and demos @alexreardon, thanks for giving the talk :)

**Comment by muralisaripalli** [comment]
I was unable to attend this months meetup. Can you upload any slides or links?
