### ISSUE TITLE
Flow: Static type checking for React Props (and more)

### ISSUE THREAD

**Issue by joshhunt** [reactsydney/talks#31]
## Talk Date

November
## Talk Title

Dr. Flowtype, or: How I Learned to Stop Worrying and Love Static Typed Javascript
## Length

I'm thinking like 15 minutes, but I haven't actually prepared anything yet. I can go for as long or short as needed.
## Twitter-sized Overview (140 characters)

Flow is a great replacement for incrementally upgrading from PropTypes to static types. Lets see how it works.
## Detailed Overview

As a millennial, I've never really seen the value in this whole 'static types' thing and avoided things like TypeScript and Flow for trying to do this in Javascript.

I'll explain how I've made the conversion into a type-loving-developer, how you can use it to replace PropTypes for a superior developer experience, how easy it is to set up and some of the things to look out for.

**Comment by jesstelford** [comment]
Hey @joshhunt are you prepared for tomorrow's meetup? If not, we can have you at our December one :)

**Comment by joshhunt** [comment]
Sure, I'm happy to present tonight :)

**Comment by jesstelford** [comment]
Thanks for the excellent and insightful talk @joshhunt!

**Comment by jgrancher** [comment]
By any chance, was the talk recorded? :)
