### ISSUE TITLE
Making Search Simple

### ISSUE THREAD

**Issue by tbillington** [reactsydney/talks#33]
**Talk Date**
Monday 5th December

**Talk Title**
Making Search Simple (working title)

**Length**
10 minutes~?

**Twitter-sized Overview (140 characters)**
Making search simple in React

**Detailed Overview**

**Comment by jesstelford** [comment]
Sounds like a great talk! We'd love to have you join us on Monday 7th November! :tada:

**Comment by tbillington** [comment]
Hey @jesstelford I'm going to postpone this until the next meet up so I can do a decent job.

**Comment by jesstelford** [comment]
Not a problem - we're looking forward to having you at our December Meetup 🎉

**Comment by jesstelford** [comment]
Hey @tbillington Are you all prepared for tomorrow night's meetup?

**Comment by jesstelford** [comment]
@tbillington Let us know if you need more time to prepare - we're finalising tonight's lineup now. The next meetup will be the first Monday of February.

**Comment by jesstelford** [comment]
Hey @tbillington, our next meetup is Feb 6th - would you like to present then?

**Comment by tbillington** [comment]
Sorry @jesstelford Might be easier to close this until I'm certain I'm available to do it ! Thanks for your patience :)

**Comment by jesstelford** [comment]
Not a problem - I look forward to seeing it when you're ready :)
