### ISSUE TITLE
The 5 Principles

### ISSUE THREAD

**Issue by bassjacob** [reactsydney/talks#34]
## Talk Date
March or later

## Talk Title
The 5 Principles

## Length
30 mins

## Twitter-sized Overview (140 characters)
Organise your code to make it maintainable, extensible and modular with just these 5 weird tricks.

## Detailed Overview
Often hailed as the first 5 principles of Object Oriented Design, the SOLID principles apply to React components as much as any code. If you find your codebase becoming a tangled web of large and unweildy multi-concern behemoths these principles will guide you in refactoring your component hierarchy.

**Comment by jesstelford** [comment]
Excellent proposal! I'll pencil you in for March and touch base closer to the date.

**Comment by jesstelford** [comment]
@bassjacob Still keen to give this talk in a month at the March meetup?

**Comment by bassjacob** [comment]
umm, I think I've overdone this one lately, I might close this for now and revisit later in the year.
