### ISSUE TITLE
TDD: Develop, refactor and deploy with confidence

### ISSUE THREAD

**Issue by mehdivk** [reactsydney/talks#35]
## Talk Date
February 2017

## Talk Title
TDD: Develop, refactor and deploy with confidence

## Length
30 mins + 5 mins for Q & A 

## Twitter-sized Overview (140 characters)
TDD: Develop, refactor and deploy with confidence

## Detailed Overview
This talk is all about test-driven development. Even if you're not using React, you will still have some learnings. For React developers, this talk will have a lot of useful information.

 * **Introduction**
   An overview of the following topics:
     * Test-Driven development
     * Unit test 
     * End-to-end/ integration tests
     * Visual regression tests
     * Snapshot tests (unique to component-based frameworks/libraries like React)
     * Best practices
  
 * **Unit tests**
     *  Best practices
     *  Libraries

 * **Snapshot tests**
    * Best practices
    * Libraries

 * **Visual Regression tests**
    * Best practices
    * Libraries

  * **More**
     * What to do after a bug report?
     * What to learn from fixing a bug?
     * and a lot more!

**Comment by mehdivk** [comment]
I saw this issue https://github.com/reactsydney/talks/issues/7 about unit testing with Mocha. Hopefully this will cover more broad areas

**Comment by bassjacob** [comment]
Looks like an awesome talk!

**Comment by jesstelford** [comment]
Great talk, love the detail in the proposal :)

Let's lock in for the February Meetup :+1:

**Comment by jesstelford** [comment]
@mehdivk How's the preparations going? All set to go for Monday?

**Comment by mehdivk** [comment]
@jesstelford G'day Jess. All set for Monday 👍

**Comment by spen** [comment]
> All set to go for Monday?

😮 Thats soon!

Looking forward to this @mehdivk :)

**Comment by mehdivk** [comment]
My presentation slide is available via Slideshare 
http://www.slideshare.net/mehdivk/tdd-develop-refactor-and-release-with-confidence

**Comment by jesstelford** [comment]
Video has been uploaded by ANZ Coders!

[TDD: Develop, refactor and deploy with confidence - 54:22](https://www.youtube.com/watch?v=luAU1zLjPMc)
