### ISSUE TITLE
Show and Tell: Guild Wars 2 Armory

### ISSUE THREAD

**Issue by madou** [reactsydney/talks#36]
I've been working on [Guild Wars 2 Armory](https://gw2armory.com) for a while, maybe it'd be something that people would like to hear about? If we don't really do this kind of thing (show and tell-ish) let me know and I'll go back to the drawing board for a different talk ! :)

## Talk Date
tbd - probably at the March or April meetup (or if theres a more appropriate theme in a later meetup)

## Talk Title
Guild Wars 2 Armory - A journey through frameworks, libraries, and development (working title)

## Length
~ 20 mins + q & a (give or take)

## Twitter-sized Overview (140 characters)
Sit down children and hear my story of developing Guild Wars 2 Armory for fun (and no profit).

## Detailed Overview
I've been developing Guild Wars 2 Armory for over a year now - hear about how I converted my front end from Angular to React, made components to share, automated everything, abused aws, and did it all for learning and fun.

**Comment by jesstelford** [comment]
Love it! It's always great to hear from people who have been through the thick of it as to learn from their experiences! 

Let us know you feel comfortable giving the talk, any month works well for us :+1:

**Comment by madou** [comment]
Awesome thanks Jess, will get back to you soon 💯

**Comment by jesstelford** [comment]
@madou, would you like to present this talk at the March 6th meetup?

**Comment by madou** [comment]
Hey dude, sure sounds good! Actually gives me a reason to start preparing things.. ! 😇

**Comment by jesstelford** [comment]
Excellent stuff - looking forward to this one 👍

**Comment by madou** [comment]
@jesstelford hey Jess ! what happens if I go over 20 minutes? :) it may be a bit longer.

**Comment by jesstelford** [comment]
Hey @madou It's fine if you go over - we'll have you up last, so you wont be holding anything up. Anything up to around 30 minutes would be perfect :+1:
