### ISSUE TITLE
Managing side-effects with redux-saga

### ISSUE THREAD

**Issue by eliseumds** [reactsydney/talks#37]
## Talk Date
March 6, 2016

## Talk Title
Managing side-effects with redux-saga

## Length
About 40min. I may also do a more detailed demo that could easily extend the talk to 60min.

## Twitter-sized Overview (140 characters)
Practical examples of how redux-saga can help you reduce application complexity by moving side-effects management to a dedicated place.

## Detailed Overview
At [ProductReview.com.au](productreview.com.au) we are developing a new version of our entire system and, after acquiring a great experience on how to handle side-effects in big and complex applications, we believe it's time to share some of them with the community so that we can all improve together.

Because Nikolay Nemshilov already did an introduction [talk about redux-saga](https://github.com/reactsydney/talks/issues/21) ([video](https://www.youtube.com/watch?v=H4I9EKGTvCE)) 7 months ago at React Sydney, this time I'd like to be a bit more practical and also explain how it works under the hood so that people that are skeptical about generators can enjoy it.

I would like to do a demo on how to create timer clocks using sagas because it's a simple and great example of a state machine. Although a timer app is fundamentally straightforward, it can cover a good part of redux-saga's API (you can see the final version [here](https://gist.github.com/eliseumds/089d65a97a2e10685952378435b33a27)).

This will (I hope) be my first talk so I'd really appreciate feedback on this [preliminary presentation](https://www.dropbox.com/s/2rxv1zej2x8ewy0/Presentation.pdf?dl=0).

## Technical requirements

A mic desk stand so that I can talk while coding. If the room has nice acoustics, I could simply speak louder.

**Comment by cyl19910101** [comment]
Would you cover the comparison between redux-saga with redux-thunk+async?

**Comment by eliseumds** [comment]
@cyl19910101 yes. There's a slide where I show an example of auth flow using an async action creator, and then I talk about the limitations of it and how it makes testing harder.

By the way, I just updated the presentation with some neater diagrams.

**Comment by jesstelford** [comment]
Great talk proposal! Let's lock it in for March 6th, 2017.

60 minutes is the maximum time we can allocate per talk - did you want to take that time, or keep it at 40 minutes?

**Comment by eliseumds** [comment]
Hi @jesstelford,

TBH, I don't know if I'll be able to use exactly the amount of time I choose. Nevertheless, I'd say 40min instead of 60min.

You definitely know the crowd better than me, that's why I'd like to ask you whether I should explain what Redux or generators are before diving into the main topic.

Cheers!

**Comment by jesstelford** [comment]
Not a problem - let's write it in for 40 minutes. The best way to get a feel for how long the talk will take is to practice a few times, and take the average of the times :+1: 

RE: Crowd. It's approximately 50% new users to React. Safe to assume familiarity with ES5, but may be a good idea to add a slide for a review of generators. The audience should know the basic concepts of what Redux is, or at least infer the functionality from context of your talk.

**Comment by JedWatson** [comment]
I'm looking forward to this one! 😀

**Comment by veebuv** [comment]
Super keen for this! I've been trying to get my staff to use it and this would be the perfect real life application of it!

**Comment by eliseumds** [comment]
@jesstelford thanks for the feedback! The basics of generators will be covered and the Redux flow will be hopefully easy to grasp from the diagrams and after seeing the actions being fired in the DevTools. I also got feedback from the library creator that, apart from liking it, made some remarks that I took into consideration.

@JedWatson @veebuv I hope it's going to useful for you and for everyone else. See you soon on the 6th!

**Comment by jesstelford** [comment]
Hey @eliseumds all prepared for tomorrow? We've got you up second (after pizza) with a 40 minute slot.

**Comment by eliseumds** [comment]
Hi @jesstelford, yes. It sounds good after pizza =) see you!

**Comment by mehrdaad** [comment]
@eliseumds do you have a public repo you demonstrated in that talk?

**Comment by eliseumds** [comment]
@mehrdaad unfortunately not, but here is my recommendation to start with: https://github.com/DerekCuevas/friend-list. This one is also interesting: https://github.com/kuy/redux-saga-examples

**Comment by mehrdaad** [comment]
@eliseumds will check it, but I think that would be nice to open source the code you demonstrate in video. at least part of it, since you perspective in managing analytics, notifications and user behaviour study with redux saga seems really intuitive.
