### ISSUE TITLE
A simplistic, fast cloud storage application

### ISSUE THREAD

**Issue by veebuv** [reactsydney/talks#38]
**Talk Date**
Monday, March 6, 2017

**Talk Title**
Create your own private - simple dropbox using React and Node

**Length**
25-30 minutes

**Twitter-sized Overview (140 characters)**
Combining React, Node and S3 to create a dynamic file uploader you can access from anywhere with internet.

**Detailed Overview**
We walk over a deployable frontend (React) and backend (node - s3) architecture in building your very own basic implementation of a basic cloud repository. We work with node's multiparty and with xmlHTTPRequests to pipe data and to our node server which then pipes (sends data in chunks) to amazons S3 service. The data once uploaded is reflected with a link, this link can then be emailed to individual email address you'd like.

Since 50% of the visitors to the meetup may be new to React, this would be a fun example of React with Redux, minus all the millions of libraries on making a simple, fun, and a practical example.

Since this would be my first talk, I'd love your thoughts on combining slides and code walkthrough vs exclusively one or the other.

**Comment by eliseumds** [comment]
That sounds interesting! We've been doing that at the company and we also leverage Lambda to create image thumbnails.

One question though: why would you need to pipe this data through a NodeJS server when you could do it directly from the browser? Do you do any kind of transformation or metadata extraction in there?

**Comment by veebuv** [comment]
Hey @eliseumds ! 

Thats awesome! Yeah i've been looking at lambda, honestly its really great, trying to kill the stigma of pure cloud driven products. 

Great question! We most certainly can do that, few reasons we have a backend system - which in this case can certainly seem unnecessary

If you were to create temporary uploading abilities to someone else, you'd want an appropriate folder for that file to sit in, now i know S3 doesn't do 'folders' but file paths 'emulate' folders is what I believe.

So yes you are correct it's basically for extracting metadata, saving it in the DB for future. Again, its just in context to this app - it most certainly can be done purely on front end (because S3 is that awesome) but with a BE we can couple it with a authentication system, add emailing and all that fun jazz :)

**Comment by madou** [comment]
sounds cool @veebuv ! you thinking about doing some live coding? imo i think slides and code walkthrough would be the best. explain concepts in slides, show examples in code.
 
sure @eliseumds while you can get the url signed (with expected values) and then upload straight to s3 im sure this is more of an intro example not the gold standard ;-)

**Comment by veebuv** [comment]
@madou I was thinking of doing a little live coding, maybe have it broken, walk through some concepts, implement that concept and then see it work! Awesome, I think that works relatively well also!

And yes like you mentioned, this is more for a demonstration that this can be done, as to it's the only right way, like a learning example if you may have ;)

Also, thanks for the interest :D

**Comment by eliseumds** [comment]
@madou that's right. Showing how to sign the request might be too much for the talk. Libs like [node-s3-client](https://github.com/andrewrk/node-s3-client) can do the hard work.

**Comment by jesstelford** [comment]
Hey @veebuv, totally missed this proposal - apologies for not getting back to you sooner.

If you're prepared for tomorrow, we'd love to have you up first (before pizza) - kicking off at 6:20, with a 30 minute slot?

**Comment by veebuv** [comment]
Hey @jesstelford No worries at all!

I was prepared for tomorrow, but unfortunately since I didn't get a confirmation I took up to lecture a JS class at coder factory! I'll be pretty solid to go for the next meet up :)

Really looking forward to it! :D

Just as a brief I was going to cover ontop of this, batch processing on setState, and why using functional callbacks is important to prevent asynchronous bugs

30-35 mins should be perfect :)

Do let me know so i'll book out that date!

**Comment by jesstelford** [comment]
Not a problem; let's lock you in for the April meetup :+1:

**Comment by veebuv** [comment]
@jesstelford That is awesome!, I'll see you then :D

**Comment by veebuv** [comment]
@jesstelford still good for Monday ?

**Comment by jesstelford** [comment]
All systems are go! 🎉
