### ISSUE TITLE
React - We use it

### ISSUE THREAD

**Issue by darrennolan** [reactsydney/talks#4]
Spit balling ideas at 10:30 tonight.  So I'm seeking feedback on what anyone would be interested in. I will do my hardest to convince the rest of my team to speak (most are attending).  I'm sure personally I'm dreadful at the task of public speaking.

**Talk Date**
Feb 8

**Talk Title**
Fox Sports - Where we use React on the new site

**Length**
Depends on the topics. Personally I'd be happy to do a short anything on any range of things.
We could maybe have a few of our team here present quick 10 minute topics.

**Twitter-sized Overview (140 characters)**
Quick mixed talks from our team about where we used react, how awesomesauce it is, and epic things achieved using React as our DOM manager.

**Detailed Overview**
We could talk about....

- Our Isomorphic/Universal react platform (server/client rendering)
- FRP and React (we use baconjs streams)
- Using react without the component lifecycle (with VideoJS / D3 and doing cool stuff)
- Componentized modules and keeping CSS at the same level.
- Using react solely on the server (because really, React+JSX is pretty rad).

I'm sure there's a lot more little interesting topics we could briefly cover, I'll add more when I can tomorrow after I chat with the team. Alternatively if there's one or two things of real interest here, we could cover those in more detail than lots of little topics.

**Comment by jesstelford** [comment]
They're all great ideas! And it'd be fine if you had multiple speakers - we can treat it as one, 50 minute talk, with each speaker taking 10 minutes each. Keep it all in 1 slide deck to keep it rolling along smoothly, and it'd be a great grab-bag of experiences to present!

Have a chat with your team, and solidify some more of the ideas / speakers, then post back here with updates :)

**Comment by darrennolan** [comment]
I can confirm 4 people are willing to talk about the cool things we've done.
We're discussing topics and things now that we could smash out really quickly while still being informative/helpful.

**Comment by jesstelford** [comment]
Awesome!

If you want to go in depth, you can always talk at the next meetup too. Or if there's one of the talks that folks are particularly interested in afterwards, you could do a longer one next time around.

**Comment by jesstelford** [comment]
@darrennolan Let's lock you in for a 50 min slot - that gives you time for the 4 speakers @ 10min each, and a couple minutes at the end for Q&A. It's going to be fun!

**Comment by darrennolan** [comment]
@jesstelford Yep, we're discussing/confirming topics that'll hopefully be awesomesauce for everyone, but we'll be there.

**Comment by jesstelford** [comment]
Tasty, tasty awesomesauce!

**Comment by jesstelford** [comment]
@darrennolan We'll get you and your team up to talk 3rd; around 8pm as long as the earlier talks are on time :) If we're running late, we'll have to keep Q&A time, and change-over time between your speakers to a minimum.

I'm really looking forward to this one!

**Comment by darrennolan** [comment]
Sounds good.

The intention is to keep change between speakers totally fluid (we're on the same set of slides, just swap to the next person) and QA we'll hold off to the end of the talk.

We're going to cover (mostly high level with some examples);

- Why we went react. (Super quickly) Performance gains/etc. there
- Working with 3rd party libs (overriding the component lifecycle flow)
- Complex Business Logics - keeping views lean and our output high (touching FRP and view composition)
- Lean intro to our Isomorphic platform and the gains for having react render those
- finishing up one what we're about to do next with react.

\o/
