### ISSUE TITLE
Introduction to Jest testing framework

### ISSUE THREAD

**Issue by koresar** [reactsydney/talks#40]
## Talk Date
Any upcoming date

## Talk Title
Introduction to Jest testing framework

## Length
30 min including QnA

## Twitter-sized Overview (140 characters)
Quick overview of why Jest is so different, why using it saves time, money, improves moral, and test coverage comparing to other frameworks.

## Detailed Overview
This is an entertaining talk about the [Jest testing framework](https://facebook.github.io/jest/). You'll laugh throughout the slides. Also you'll learn how to start or convert a project to Jest.
This talk was first given at the Sydney Node Ninjas meetup in February.

-----

The talk better be the last talk of the evening since some people already saw it and might wanna leave earlier.

**Comment by jesstelford** [comment]
Hey @koresar - great proposal! Want to give the talk at the April 3rd Meetup?

**Comment by koresar** [comment]
Sure Jess!

**Comment by jesstelford** [comment]
Hey Vasyl, are you still able to present at React Sydney?

**Comment by export-mike** [comment]
@koresar hey thanks for the talk this week! Just wondering if you have the slides available :D 👍

**Comment by koresar** [comment]
@export-mike can easily share. What format you'd like? (The best viewing experience is in the Apple Keynote app).

**Comment by koresar** [comment]
Here is the PPTX
https://www.dropbox.com/s/hl4o25e4fij3j08/jest.pptx?dl=0
Somewhat off, but looks good.
Cheers

**Comment by export-mike** [comment]
hey @koresar thats great thanks! :D
