### ISSUE TITLE
Reacting Reasonably

### ISSUE THREAD

**Issue by bassjacob** [reactsydney/talks#41]
## Talk Date
June?

## Talk Title
Unreasonable Expectations

## Length
30 minutes

## Twitter-sized Overview (140 characters)
ReasonML is one of the current bets that were all going to be writing typed fp in the future. This talk is an overview into building a universal reactjs app with ReasonML

**Comment by jesstelford** [comment]
Ooh, nice one! Let's lock it in for the May 1st Meetup 👍

**Comment by bassjacob** [comment]
Sounds good to me :smile: I'll flesh the description here out a little more when I have some more of it written

**Comment by jesstelford** [comment]
@bassjacob Still good to go for May 1st?

**Comment by bassjacob** [comment]
Hey @jesstelford ,

Still on for June?

**Comment by jesstelford** [comment]
We are! You ready to give your talk?

**Comment by bassjacob** [comment]
Definitely 😄

**Comment by jesstelford** [comment]
We'll have you up second tonight, really looking forward to it, this will be my first exposure to ReasonML! 🎉
