### ISSUE TITLE
React Code Splitting and Long Term Caching

### ISSUE THREAD

**Issue by veebuv** [reactsydney/talks#42]
## Talk Date
May

## Talk Title

Code Splitting is easy

## Length

30 - 40 minutes
## Twitter-sized Overview (140 characters)
We'll talk about route level splitting and vendor caching. With Webpack 2's tree shaking we can also work with lazy importing components. 

## Detailed Overview
Will fill in ASAP

**Comment by veebuv** [comment]
@jesstelford has this been covered before ?

**Comment by jesstelford** [comment]
@veebuv I don't remember this topic being covered yet, and it's an important one! I'll put you in for the May 1st  meetup 👍

**Comment by veebuv** [comment]
@jesstelford done! See you then :)

**Comment by jesstelford** [comment]
@veebuv All prepared for the meetup tonight?

**Comment by cyl19910101** [comment]
@veebuv Thanks for the ideas of how to split code! Are you going to upload the example that how to async load React Component after switch route path?
