### ISSUE TITLE
Progressive Web Apps with React

### ISSUE THREAD

**Issue by veebuv** [reactsydney/talks#45]
## Talk Date
June

## Talk Title
Progressive Web Apps with React and what this means for future development

## Length
30-40

## Twitter-sized Overview (140 characters)
PWAs are coined to be the next big development in web, basically follows extreme caching and webworkers, some big names are using it, and you should to

## Detailed Overview
Talk in detail about what PWAs are, how we can use them. Future of web mobile applications and browsing. A short but detailed coverage about async - dynamic redux store in combination with code split routing

**Comment by jesstelford** [comment]
Great topic, and one I hope more and more folks are getting familiar with!

Do you mind if we have this at the July meetup?

**Comment by veebuv** [comment]
Hey @jesstelford sounds perfect to me!!!

**Comment by jesstelford** [comment]
Hey @veebuv Still good to present on July 3rd?

**Comment by jesstelford** [comment]
Hey @veebuv - At this point I'll put you down as speaking, but if you're not able to make it, please let me know :+1:

**Comment by veebuv** [comment]
@jesstelford good to go, apologies i didn't see this till now

**Comment by jesstelford** [comment]
Great to hear :) we'll see you tonight!
