### ISSUE TITLE
Redux-First Routing With Redux-Little-Router

### ISSUE THREAD

**Issue by justrossthings** [reactsydney/talks#46]
## Talk Date
June or July

## Talk Title
Redux-First Routing With Redux-Little-Router

## Length
15-20

## Twitter-sized Overview (140 characters)
With the standard react-router implementation, url state and redux store were kept in separate buckets and managed separately. Redux little router brings url state into redux store to defeat this anti-pattern.

## Detailed Overview
The first part of the presentation will explain why url state and redux store being separate is not good, [summarising from these blog posts](http://formidable.com/blog/2016/07/11/let-the-url-do-the-talking-part-1-the-pain-of-react-router-in-redux/) by the redux-little-store creators. 

After the problem has been explained I will demonstrate use of redux-little-router in a demo application going through it's implementation and use in a react-redux application.

**Comment by jesstelford** [comment]
Great proposal! If it's not too short notice, we'd love to have you at the June 5th meetup :) Otherwise, July 3rd.

**Comment by justrossthings** [comment]
@jesstelford Ok great. I can do June 5

**Comment by jesstelford** [comment]
We'll have you up first tonight, Ross. I'm looking forward to it :)

**Comment by jesstelford** [comment]
Thanks for the talk @justrossthings! If you've got your slides online, it'd be great to link them from this issue for prosperity :+1:

**Comment by justrossthings** [comment]
@jesstelford sure! 🙌  - https://goo.gl/RupJeB
