### ISSUE TITLE
React and GraphQL at the Powerhouse Museum

### ISSUE THREAD

**Issue by unkleho** [reactsydney/talks#47]
## Talk Date
June or July

## Talk Title
React and GraphQL at the Powerhouse Museum

## Length
10-20mins

## Twitter-sized Overview (140 characters)
At the Powerhouse Museum (part of MAAS), we have completely rebuilt our online catalogue of 140,000 objects using React (Universal JS), GraphQL and Elasticsearch. [https://collection.maas.museum](https://collection.maas.museum)

## Detailed Overview
The collection application ([https://collection.maas.museum](https://collection.maas.museum)) was originally based on this [React Starter Kit](https://github.com/kriasoft/react-starter-kit). We also used Redux, [Apollo](https://github.com/apollographql/react-apollo) as our GraphQL client and [Searchkit](http://www.searchkit.co/) to build the UI for in-depth object search powered by Elasticsearch. Styles are handled by PostCSS, with help from the [Lost](https://github.com/peterramsing/lost) grid library.

On the API side, we have opened up our [GraphQL API](https://api.maas.museum/docs/graphql). We've used [graphql-compose](https://github.com/nodkz/graphql-compose) and [Mongoose](https://github.com/Automattic/mongoose) to build our GraphQL server. We've also combined this with [KeystoneJS](http://keystonejs.com/) to effectively build a headless GraphQL CMS. For even more fun, we are pulling in data from our Wordpress site too.

We really pushed the boundaries here and learnt a bunch of lessons for next time round. 

Not sure if these topics have been covered before, but very happy to share them as a talk or just a chat at the next meetup.

Cheers
Kaho (unkleho)

**Comment by jesstelford** [comment]
This is an excellent real-world example! We definitely need more of these kinds of "here's how we did it" talks. I'd love to have you present it at the July 3rd meetup 👍 

You're welcome to talk for up to 60 minutes (or 10minutes, whatever works best for you) :)

**Comment by unkleho** [comment]
July 3rd sounds great. Perhaps 25-30mins might be a good idea. I'll have a better idea as I put some slides together. 

I'll try and come down to the June meet up next week. Thanks

**Comment by jesstelford** [comment]
Hey @unkleho 25-30 minutes is perfect. Are you still able to present on July 3rd?

**Comment by unkleho** [comment]
Hi Jess, yes, no problem. See you then.

**Comment by export-mike** [comment]
hey @unkleho I was wondering if the slides from your presentation are available? 👍  enjoyed your talk!

**Comment by unkleho** [comment]
Hey Mike, thanks!
Finally got the slides up - https://github.com/unkleho/react-sydney-meetup-2017
Cheers
