### ISSUE TITLE
Graphql and React Relay

### ISSUE THREAD

**Issue by bochen2014** [reactsydney/talks#48]
**Talk Date**
June or July

**Talk Title**
Graphql and React Relay

**Length**
30~40 minutes

**Twitter-sized Overview (140 characters)**
Want to give an introduction on how `graphql` and `relay` are used at [unibet racing client](https://www.unibet.com.au/racing). How it helps to reduce the amount of http request and how it makes data access easier (potentially how it's different from `redux`)

**Detailed Overview**
probably an introduction to `graphql` first (not sure if this necessary) and then focus on the use of `relay`. Our project is not open-sourced so I probably will use a [relay example](https://github.com/relayjs/relay-examples) instead to explain/demo how to use it in react application

**Comment by jesstelford** [comment]
Hey @bochen2014 - This is a great talk proposal. Are you able to do it at the July 3rd meetup?

An introduction to graphql can't hurt - about 50% of the audience are new to react :+1:

**Comment by bochen2014** [comment]
no problem.  thanks Jess. will talk about it on 3rd July.

**Comment by justrossthings** [comment]
Hyped for all the GraphQL at the next meet 🔥
