### ISSUE TITLE
Typed React and the creation of custom PropTypes

### ISSUE THREAD

**Issue by rocking42** [reactsydney/talks#49]
## Talk Date
August

## Talk Title
Typed React and the creation of custom PropTypes

## Length
20-25 mins

## Twitter-sized Overview (140 characters)
When the current PropTypes don't suit all your need create your own. This talk will go through some use cases for when you may need custom PropTypes, the creation as well as how to test and the pain point we have found using them in production.

## Detailed Overview
In our current project we found that the conventional PropTypes that React offered didn't cover all our use cases. The way around this was to just build them from scratch. During this process we ran into a range of problems with how they would work with existing PropTypes as well as with other custom props.

Another major problem came when testing these custom PropTypes. This talk will go through how we overcame these issues, including both mocha and jest solutions.

**Comment by jesstelford** [comment]
Oooh, this is a very interesting topic! Deep dives like this really help spread the knowledge.

We might not be able to fit you into the August meetup, but for now we'll put you down as a _maybe_ depending on how some of the other proposals work out.

**Comment by rocking42** [comment]
Sounds good @jesstelford let me know how it goes in regards to the August meetup.

**Comment by jesstelford** [comment]
Hey @rocking42 we'd love to have you at our August 7th meetup - are you still able to present?

**Comment by rocking42** [comment]
Sounds good @jesstelford. I'll be there for sure!

**Comment by jesstelford** [comment]
We'll have you up second tonight, after the pizza, so everyone will be fuelled up and ready to listen :)
