### ISSUE TITLE
Functional Programming in relation to React/Flux, Front End Development & JS in general 

### ISSUE THREAD

**Issue by halhenke** [reactsydney/talks#5]
**Talk Date**
Feb 8th I guess

**Talk Title**
Functional Programming: Its Influence on React, Facebook's Javascript Ecosystem and modern Front End Development in General

...or something better

**Length**

I suppose if it was kept to something like `Immutable.js` and the use of immutable data in React it could be a shorter talk whereas if it opened up to discuss ideas from FP as a common theme in React/Flux/Immutable.js it would be a longer 20-30 minute talk - could touch on Elm & other things also?

**Twitter-sized Overview (140 characters)**

In the past few years Facebook has released a set of highly influential tools, that draw on many ideas from Functional Programming 

**Detailed Overview**

- Some FP/OO background
  - Key FP ideas
- DOM mutation and state
- Functional aspects of React, Flux, Immutable.JS (Flow maybe)
- How Immutability can help React code in particular
- Not just React - Elm/CycleJS, Clojurescript & other FE, FP tools
- Some FRP stuff maybe...
- etc

Not sure if this fits the proposed theme for the night or not...

**Comment by nkbt** [comment]
That would be pretty cool!

**Comment by jesstelford** [comment]
Sounds like a great fit!

Feel free to choose the length of the talk, anywhere up to around 50 minutes (then 10 minutes for some Q&A). Depending on the number of other proposals we get, it could be a squeeze, but if it's popular enough, it'd be great to dive in deep :)

**Comment by jgrancher** [comment]
That sounds pretty interesting! :+1:

**Comment by jessicace** [comment]
:+1: You should totally call the talk FPIIoRFJE&MFEDiG though.

**Comment by halhenke** [comment]
Cool - thanks for the encouragement guys

Will work on it over the weekend and will have a good idea of how long it will be in a few days I guess. At this stage I will prob aim for around 30 minute mark I think.

And thanks @jessicace, thats the best alternative name anyone has suggested so far. I mean that.

**Comment by jesstelford** [comment]
@halhenke A 30 min talk is great. Let's lock that in for the 8th :)

**Comment by halhenke** [comment]
Cool!

**Comment by jesstelford** [comment]
@halhenke We'll get you up to talk 2nd, at around 7:20/7:30.

**Comment by halhenke** [comment]
@jesstelford No worries :+1:

**Comment by jesstelford** [comment]
Looking forward to it! :D
