### ISSUE TITLE
Things I learned building a large-scale site in React

### ISSUE THREAD

**Issue by lid2000** [reactsydney/talks#50]
## Talk Date

August

## Talk Title

Things I learned building a large-scale site in React

## Length

25 - 30 minutes

## Twitter-sized Overview (140 characters)

CAPA opted to rebuild their entire website as a React app. Here's what they ran into along the way. https://centreforaviation.com

## Detailed Overview

In May, CAPA - Centre for Aviation relaunched [our website](https://centreforaviation.com), which was the culmination of a 12-month ground-up rewrite of our entire internal systems. The entire site frontend now runs as one giant (385 components and counting) client-side React web app that speaks directly to our REST API, emulating the look of a traditional site while allowing total flexibility over... well, everything.

We started out as total noobs to React and Node, and finished being able to write ES6 in our sleep. This talk covers the trickiest problems we ran into along the way (some React, some general Node), dealing with things like:

* Webpack, code splitting, and the neverending quest to get the initial code bundle as small as possible
* Cancelling Promises: reasons you'd want to do this, and how
* Server-side rendering of asynchronous data: SSR is relatively straightforward, but when it needs to include async data then things get a bit nasty
* CSS modules: super useful when styling anything substantial
* Old mate Internet Explorer: we abandoned support for anything below IE11, but as is the tradition, IE11 still gives its fair share of grief (Edge sometimes sneaks in some stuff too)
* Syncing Redux between browser tabs/windows: mostly easy, but with one big gotcha
* Ditching mixins and moving to ES6: this was painful
* Asynchronously loading reducers: useful for bringing that code bundle size down
* Clustering: we realised the importance of this after getting smashed with traffic at launch

**Comment by veebuv** [comment]
This is great! Especially async loading reducers, many people don't realise that it's important and especially when you've code split the application!

**Comment by joshhunt** [comment]
👍 

@jesstelford i wonder if there's interest in doing a 'retro' edition of React-Sydney? If appropriate, I might have a few words to spill about the experience from Nine and Qantas... 👀

**Comment by jesstelford** [comment]
This is an excellent talk proposal! Really love these real-world examples!

@joshhunt Hmm, that could be a great idea! Please do pop in a proposal - with 1 more on top, we could spread it out over 2 months, with yours in September.

**Comment by jesstelford** [comment]
Hey @lid2000 we'd love to have you at our August 7th meetup - are you still able to present?

**Comment by lid2000** [comment]
I really want to, but honestly I don't see myself having enough time to put together a decent presentation within the next week. I'm getting smashed at work. Can we try again in September?

**Comment by jesstelford** [comment]
No problem mate, let's pencil you in for September 👍

**Comment by jesstelford** [comment]
@lid2000 how's September 4th for you?

**Comment by lid2000** [comment]
I'll be in Japan unfortunately. I think I'll have to give up on this for now - if things free up in a few months I'll give it another try. Thanks for considering me though!
