### ISSUE TITLE
Going on a diet with Preact

### ISSUE THREAD

**Issue by justrossthings** [reactsydney/talks#51]
## Talk Date
Aug

## Talk Title
Going on a diet with Preact

## Length
15-30 mins

## Twitter-sized Overview (140 characters)
Get your apps summer-ready with Preact, 3kB alternative to React with the same ES6 API

## Detailed Overview
A overview of Preact and it's use-case, a implementation of preact, and a migration guide for react => preact

**Comment by jesstelford** [comment]
Ooh, a competing framework! Love it :)

We've gotten a few submissions for August already, so I'll have to confirm closer to the date whether we'll have you at that or a future meetup.

**Comment by justrossthings** [comment]
thanks @jesstelford

**Comment by jesstelford** [comment]
Hey @justrossthings we'd love to have you at our August 7th meetup - are you still able to present?

**Comment by justrossthings** [comment]
@jesstelford yes my dude. Cya then 👋

**Comment by jesstelford** [comment]
We'll have you up first tonight, just before we do Pizza 👍
