### ISSUE TITLE
Beautiful drag and drop for the people

### ISSUE THREAD

**Issue by alexreardon** [reactsydney/talks#52]
## Talk Date
August meetup

## Talk Title
Beautiful drag and drop for the people

## Length
20-30 minutes

## Twitter-sized Overview (140 characters)
Introducing a new library for physics based drag and drop that is highly performant and keyboard first.

## Detailed Overview
This is building on some of my prior work (and talks) on this topic. I have been refining concepts and completely rebuilt the api to allow for more generic usage.

**Comment by alexreardon** [comment]
@JedWatson ^

**Comment by alexreardon** [comment]
@jesstelford I am keen to give this at the August meetup as I might be away for September.

**Comment by jesstelford** [comment]
Let's do it! 👍

Sorry for the delay in getting back to you

**Comment by jesstelford** [comment]
We'll have you up last (3rd) tonight - am looking forward to it! 👍
