### ISSUE TITLE
Integrated UI testing with React

### ISSUE THREAD

**Issue by alexreardon** [reactsydney/talks#53]
## Talk Title
Integrated UI testing with React

## Length
15-20m

## Twitter-sized Overview (140 characters)
Exploring how React testing utilities can be a valuable replacement for traditional integration testing tools and techniques.

**Comment by alexreardon** [comment]
I am also happy to give this one ^ @JedWatson 
I am on parental leave the month after so it will be the last chance until Nov

**Comment by jesstelford** [comment]
@alexreardon to clarify; you're out now, and can no longer give this talk?

**Comment by alexreardon** [comment]
I *should* be able to make it! I'll let you know if something changes

**Comment by jesstelford** [comment]
Excellent to hear! Are you happy to give this talk for our September 4th meetup?

**Comment by alexreardon** [comment]
Yep!

**Comment by jesstelford** [comment]
Locked in! 👍

**Comment by alexreardon** [comment]
![enhanced-buzz-28895-1301694293-0](https://user-images.githubusercontent.com/2182637/29817879-19fa39e4-8cfd-11e7-94cf-e7461d02c660.jpg)

**Comment by jesstelford** [comment]
@alexreardon We've got you up as the final speaker of the evening. Probably around 19:45 - 20:00.

**Comment by alexreardon** [comment]
![pingu2](https://user-images.githubusercontent.com/2182637/30010407-e23010e0-9172-11e7-8e5a-77ae68d5fa22.gif)
