### ISSUE TITLE
ReVue ?

### ISSUE THREAD

**Issue by veebuv** [reactsydney/talks#54]
## Talk Date
When available

## Talk Title
ReVue - React and Vue can learn a lot from each other

## Length
20 mins

## Twitter-sized Overview (140 characters)
Vue has gained alot of traction, mainly from React engineers due to simplified patterns, after using both, there's strong patterns we can see and learn from both

## Detailed Overview
TBA - but brief break down on intro to Vue for React people, why both are good and don't compete, they are a partnership.
Patterns to share from both environments

**Comment by veebuv** [comment]
Not sure if this will be allowed, but i've had alot of people ask me for a detailed comparison of the two, i'll be writing a blog on it, but more than happy to present! Let me know if cool @jesstelford @JedWatson

**Comment by veebuv** [comment]
Any thoughts on this @jesstelford ?

**Comment by jesstelford** [comment]
Sorry for the slow response @veebuv!

We'd love to have a comparison to Vue! Are you able to present at the September 4th meetup?

**Comment by veebuv** [comment]
@jesstelford all good - would we be able to fit it into the October meet up - it would be a push to get all the slides in by next week. Let me know, if not - I can push ahead and make it happen :)

**Comment by jesstelford** [comment]
October is good 👍

**Comment by veebuv** [comment]
Schweeet! See you then :) and next week for the event as well!

**Comment by jesstelford** [comment]
We've cancelled the October event (it's a public holiday), so we'll have your talk at a following meetup. Looking forward to it :+1:

**Comment by veebuv** [comment]
Sure thing, let me know when you'd like that to happen :) @jesstelford

**Comment by jesstelford** [comment]
@veebuv would the December 4th meetup work for you?

**Comment by veebuv** [comment]
Hi @jesstelford that should be fine :)

**Comment by jesstelford** [comment]
Hey @veebuv, confirming you're still available to give your talk at the Monday, December 4th meetup?

**Comment by veebuv** [comment]
Still good to go @jesstelford

**Comment by jesstelford** [comment]
Excellent! We're going to have a full schedule on Monday, so keep the 20 minute time limit in mind as you prepare 👍

**Comment by veebuv** [comment]
Yup, this will be a short one, so well within 20 min
