### ISSUE TITLE
Visual regression testing: easier than you think

### ISSUE THREAD

**Issue by Li0liQ** [reactsydney/talks#55]
## Talk Date
August/September

## Talk Title
Visual regression testing: easier than you think

## Length
15-25 minutes

## Twitter-sized Overview (140 characters)
You don't need end-to-end testing in order to have VR testing. As long as you have dumb components and a storybook, adding VR testing is a breeze.

## Detailed Overview
Visual regression testing is seen as something very helpful but difficult to implement/maintain.
This is no longer the case with storybook.
The talk will give an overview of our approach to implementing visual regression testing for JIRA and mention some of the pitfalls to be aware of. There is also an option to delegate it if you don't want to own the service.

**Comment by jesstelford** [comment]
@Li0liQ This is an excellent topic! Are you able to present at our September 4th meetup?

**Comment by Li0liQ** [comment]
@jesstelford Sure, let's do that.

**Comment by jesstelford** [comment]
Perfect 👍

**Comment by jesstelford** [comment]
@Li0liQ We'll have you up first tonight - come grab me before we get started so we can test your laptop on the screen, etc 👍
