### ISSUE TITLE
Earl Grey: Demystifying "The Elm Architecture" and Redux-alikes

### ISSUE THREAD

**Issue by bassjacob** [reactsydney/talks#56]
## Talk Date
November forward

## Talk Title
Reading the TEA leaves

## Length
30 minutes or so

## Twitter-sized Overview (140 characters)
There have been a number of talks given on how to use Redux/The Elm Architecture, but no talks on how to write it...

## Detailed Overview
TBD

**Comment by jesstelford** [comment]
You're a research machine! Love to hear about Redux + Elm, and I'm sure others would too.

I'll put you in for November, and confirm again closer to the date :+1:

**Comment by jesstelford** [comment]
Confirmed offline.

**Comment by jesstelford** [comment]
Thanks for the great talk last month @bassjacob - if you have any resources to share (slides, etc), feel free to post them here :+1:
