### ISSUE TITLE
Render to whatever with React

### ISSUE THREAD

**Issue by Raathigesh** [reactsydney/talks#57]
## Talk Date
September or October

## Talk Title
Render to whatever with React (May be I should work on a better title! Not convinced!)

## Length
30 mins

## Twitter-sized Overview (140 characters)
Creating a custom renderer with React fiber

## Detailed Overview
I recently created a custom renderer which renders to an express app (It's not a good idea and but did it anyway to explore the fiber reconciler API).  In this talk, I would like to introduce the other awesome custom renderers available out there and give a quick walkthrough of how to create a custom renderer for yourself.

**Comment by bassjacob** [comment]
So you build a React Component hierarchy that generates an express app? That sounds really cool :smile:

**Comment by Raathigesh** [comment]
Yes, it does. https://github.com/Raathigesh/react-atmo 😄

**Comment by bassjacob** [comment]
that is so cool!

**Comment by jesstelford** [comment]
This would be an excellent talk for our October meetup! Let's lock it in @Raathigesh 🎉

**Comment by Raathigesh** [comment]
Sounds good! I'll start preparing 😄

**Comment by jesstelford** [comment]
We've cancelled the October event (it's a public holiday), so we'll have your talk at a following meetup. Looking forward to it :+1:

**Comment by jesstelford** [comment]
Hey @Raathigesh would you be able to give this talk at our November 6th meetup?

**Comment by Raathigesh** [comment]
Hey @jesstelford, Sure! Let's do it!

**Comment by jesstelford** [comment]
:tada:

**Comment by jesstelford** [comment]
@Raathigesh Come say hi tonight around 6:10 so we can get you in the order for speaking 👍

**Comment by Raathigesh** [comment]
@jesstelford Will do!

**Comment by jesstelford** [comment]
Thanks for the great talk last month @Raathigesh - if you have any resources to share (slides, etc), feel free to post them here :+1:
