### ISSUE TITLE
Patent Infringement Claims on React Open Source Licensing

### ISSUE THREAD

**Issue by MincePie** [reactsydney/talks#58]
**Talk Date**
I could do it at the Sept meetup. 

**Talk Title**
As above

**Length**

10 mins
**Twitter-sized Overview (140 characters)**
The implications of the patent grants termination clause included in the React license.

**Detailed Overview**

Is the community interested in breaking down the termination clause included in React's license? I left my career after 10+ years in law (sydney and london) then structured finance trading, to (learn to code and) build a startup trying to deliver opportunities to use structured finance to fund basis science research. 

We could briefly step through the clause, the carve-outs and the practical implications.

**Comment by jesstelford** [comment]
This would be an excellent talk @MincePie!

Sorry I missed the proposal, is it too late to get you in for tomorrow (September 4th) meetup?

**Comment by MincePie** [comment]
Hi @jesstelford - tomorrow should be fine. I'm thinking a 15 min run through is probably enough for this kind of topic. I know it's not of technical interest. I'm happy to do it tomorrow.

**Comment by jesstelford** [comment]
That'd be a great time, and will fit nicely to break up our other two talks. Thank for doing it on such short notice :+1:

**Comment by jesstelford** [comment]
@MincePie We'll have you up second tonight, after we have pizza. It'll be at around 19:30 - 19:45. Feel free to come introduce yourself and we can test out your laptop, etc during the break 👍

**Comment by veebuv** [comment]
Super keen for this!

**Comment by jesstelford** [comment]
FYI: React is now MIT licensed: https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
