### ISSUE TITLE
Brownfield React: Introducing React to a "Legacy" Codebase

### ISSUE THREAD

**Issue by ttsui** [reactsydney/talks#59]
## Talk Date
November Meet-up

## Talk Title
Brownfield React: Introducing React to a "Legacy" Codebase

## Length
30 mins

## Twitter-sized Overview (140 characters)
A talk about my journey towards introducing React to an old school PHP/jQuery codebase. Some tips I've up picked along the way.

## Detailed Overview
Over the last few months I've been slowly introducing React to a PHP/jQuery codebase. I've learnt a number of things along the way which may be of interest to people who wish to take the same journey.

**Comment by jesstelford** [comment]
I know lots of folks who'd love to hear about your experiences, we'd love to have you at the November meetup!

I'll put you in now, and will confirm again closer to the date :+1:

**Comment by jesstelford** [comment]
Hey @ttsui, can we lock you in for th eNovember 6th meetup?

**Comment by ttsui** [comment]
@jesstelford Yes

**Comment by jesstelford** [comment]
@ttsui Come say hi tonight around 6:10 so we can get you in the order for speaking 👍

**Comment by jesstelford** [comment]
Thanks for the great talk last month @ttsui - if you have any resources to share (slides, etc), feel free to post them here :+1:
