### ISSUE TITLE
Asynchronous and Universal React rendering: Beyond Redux & xhr

### ISSUE THREAD

**Issue by subshad** [reactsydney/talks#6]
**Talk Date**

Anytime. Feb 8th I guess?

**Talk Title**

Asynchronous and Universal React rendering: Beyond Redux & xhr

**Length**

Something between 30mins and 1hr depending on how in depth it goes.

**Twitter-sized Overview (140 characters)**

How and why to use Component Driven Data Requirements rather than defining static fetching methods or by passing in the full atom to the root node.

**Detailed Overview**

* What's wrong with React...
  * Server side single pass
  * roots need to know way too much about leaves

* Advantage of components as data encapsulation
  * Co-locate data requirements alongside rendering code
  * Change representation and fetching in fewer places

* Disadvantages
  * Operational complexity (need some fetching and caching system)
  * Dirty tricks

* State of the art
  * react-router
  * react-transmit
  * Relay/GraphQL
  * Falcor

* Introducing Proactive
  * Walkthrough the example solution to the problem - the micro-framework
  * Use cases and drawbacks of this implementation
  * What I'd like to see in React that would make this obsolete

**Comment by jesstelford** [comment]
Very nice proposal! Always great to see a shout-out to existing OSS work too :)

**Comment by yangli1990** [comment]
+1

**Comment by jesstelford** [comment]
@subshad Let's lean toward the shorter end (30-40min), and lock your talk in for the 8th.

**Comment by jesstelford** [comment]
@subshad We'll have you up first on the night: 6:30pm. Doors open at 6pm, but feel free to come a little earlier to get setup.
