### ISSUE TITLE
React 16's New Features

### ISSUE THREAD

**Issue by bassjacob** [reactsydney/talks#60]
## Talk Date
Probably soon before it gets too old and they release a new version

## Talk Title
React 16's New Features

## Length
:man_shrugging: 

## Twitter-sized Overview (140 characters)
I thought this would make a good "first talk" for someone in the community (though I'm happy to give it if no one else does), so up to whoever takes it.

## Detailed Overview
React 16 was released. There are a tonne of great new features just waiting to be explained!

**Comment by veebuv** [comment]
Keen to hear from you!

**Comment by parkroolucas** [comment]
If no one has stepped up yet I'm happy to give it a shot!

I'm thinking about introducing the new features in React 16, but also trying to look at what this means for React as a framework, and particularly the development mindset that should be accompanied with writing React code.

**Comment by jesstelford** [comment]
@parkroolucas that'd be great! Can you [open a new talk proposal](https://github.com/reactsydney/talks/issues/new), then we can schedule the talk in :)

**Comment by parkroolucas** [comment]
@jesstelford Done!

**Comment by bassjacob** [comment]
closing now that https://github.com/reactsydney/talks/issues/66 exists
