### ISSUE TITLE
From monolith to modern front end

### ISSUE THREAD

**Issue by thirty3** [reactsydney/talks#61]
## Talk Date
November Meet-up

## Talk Title
From monolith to modern front end

## Length
30min

## Twitter-sized Overview (140 characters)
How we are introducing React, Redux and Redux-Oberservable into our legacy code bases.

## Detailed Overview
As an organisation we have decided to move away from frameworks in favor of small purpose built libraries. A large part of the choice was the ability to slowly phase in a new stack without having to rewrite our legacy code base.

This talk is about how we are introducing these changes and how we are using open source principles to increase collaboration across teams.

**Comment by jesstelford** [comment]
Love it, this will be another great point of view to compliment [this talk](https://github.com/reactsydney/talks/issues/59).

Would you be able to give this at our December 4th meetup?

**Comment by thirty3** [comment]
Hey @jesstelford 4 December definitely works

**Comment by jesstelford** [comment]
Looking forward to it, thanks :)

**Comment by jesstelford** [comment]
Hey @thirty3, confirming you're still available to give your talk at the Monday, December 4th meetup?

**Comment by thirty3** [comment]
Hey @jesstelford I am indeed. In fact I am working on it right now 😸

**Comment by jesstelford** [comment]
Excellent! We're going to have a full schedule on Monday, so keep the 30 minute time limit in mind as you prepare 👍

**Comment by Sonyque** [comment]
Hey @thirty3 ! I was on your presentation on Sydjs. It was soo exciting. Could you share your presentation somewhere on the internet?
Thanks in advance!

**Comment by thirty3** [comment]
@Sonyque Here you go 😸 

https://www.slideshare.net/LeonBezuidenhout4/from-monolith-to-modern-frontend
