### ISSUE TITLE
An introduction into A+ forms

### ISSUE THREAD

**Issue by MadRabbit** [reactsydney/talks#62]
## Talk Date
Mon 4, Dec 2017

## Talk Title
An introduction into A+ forms

## Length
The standard 20 mins + Questions i suppose

## Twitter-sized Overview (140 characters)

Remember how simple and awesome forms used to be when HTML was static? Well, I've built a
thing that give you the same development experience in React while providing a full feature set of a modern forms library

## Detailed Overview

At @shortlyster we build a lot of forms. Complex ones at that too. So, to ease the pain, i've developed a new React forms library, that makes forms development an easy and enjoyable process. It has minimal wiring, almost zero learning curve for the engineers who adopt it, and turns forms development into a simple declarative process as it used to be in plain HTML.

It worked marvelously for our team. And now I've turned it into a proper open-source project, and would like to share the merits with the broader community. Hence this talk.

The talk is basically about pain points of forms development in react. Scalability of different approaches with application complexity growth, and supportability (is that a word?) of produced code. And how we addressed the problems in `A+ forms`

https://github.com/MadRabbit/a-plus-forms

**Comment by eliseumds** [comment]
![http://i0.kym-cdn.com/photos/images/facebook/000/207/484/1322277979335.jpg](http://i0.kym-cdn.com/photos/images/facebook/000/207/484/1322277979335.jpg)

**Comment by jesstelford** [comment]
Very nice idea! We'd love to have you speak at our December 4th meetup (this coming Monday) 👍 

We're going to have a full schedule on Monday, so keep the 20 minute time limit in mind as you prepare 👍

**Comment by MadRabbit** [comment]
Awesome. Thanks Jess!
