### ISSUE TITLE
JOE (Javascript on Everything)

### ISSUE THREAD

**Issue by markspereira** [reactsydney/talks#63]
## Talk Date
04/12/2017

## Talk Title
JOE (Javascript on Everything)

## Length
5 minutes (Lightning Talk)

## Twitter-sized Overview (140 characters)
JOE allows anyone to program on an IoT device, mobile application, web application, and web server with Javascript through blockchain.

## Detailed Overview
JOE (Javascript on Everything) is an open-source project which allows anyone to develop a full suite of technology running on the blockchain or regular web protocol. It utilizes the power of Javascript Frameworks such as React for the web, React Native for mobile, NodeJS for the server, Johnny-Five for the IoT device, and Web3.js for blockchain. This is an incredibly powerful bridge that could be used across the educational sector all the way up to corporations and institutions.

**Comment by jesstelford** [comment]
Ooh, this is a great topic - I love the promise of Javascript's VM running on everything! And a lightning talk format is perfect for our December 4th meetup (this coming Monday)

We're going to have a full schedule on Monday, so keep the 5 minute time limit in mind as you prepare (if you think you'll go over, we can allocate 10 minutes for you) 👍

**Comment by markspereira** [comment]
Hey Jess!

Glad you like it! That’s awesome news, it will definitely be within the 5
minute timeframe. Thanks so much for the opportunity.

Would love to have a chat with you about the idea before hand. Maybe over
the phone or over a coffee. Let me know!

Mark
