### ISSUE TITLE
Human memory based storage model!

### ISSUE THREAD

**Issue by ajainvivek** [reactsydney/talks#65]
## Talk Date
5th February 2018

## Talk Title
Human memory based storage model!

## Length
40 mins

## Twitter-sized Overview (140 characters)

Rethinking how the state of your app stored in an object tree inside a single store can be transformed to memory model. 

## Detailed Overview

The concept of a single store is considered to be like a stack of data kept in a single place.  If we have closer look we can relate store to human memory, where data is collected in a single place. 

Working model of human memory

![Human Memory Working](http://brainmadesimple.com/memory/memory.JPG)

The similar idea can be hooked on to the single store by storing the data into memory model and retrieving back.

WIP sourcecode: [Link](https://github.com/ajainvivek/react-memory)

**Comment by jesstelford** [comment]
Let's do it! Feb 5th, locked in.

Thanks for being patient while I get back into the organisational things :)

**Comment by jesstelford** [comment]
@ajainvivek can you confirm the length of your talk for Monday night? Thanks.

**Comment by ajainvivek** [comment]
@jesstelford Maybe around 30-40 min max.

**Comment by jesstelford** [comment]
Perfect! We'll have you as the third speaker for the night, around 7:45-8:00 (depending on if we run over with the earlier speakers).

**Comment by ajainvivek** [comment]
@jesstelford Is it possible to push the talk bit earlier? I have something to take care of. Sorry for the late notice.

**Comment by jesstelford** [comment]
Yep, we can get you up first for the evening, around 6:30, does that work?

**Comment by ajainvivek** [comment]
@jesstelford Yes, that works. Thanks mate 👍

**Comment by jesstelford** [comment]
Sorry, do you mind if we have you up second? That would have you kicking off around 7:20 - what time do you need to leave?

**Comment by ajainvivek** [comment]
That should be fine. Can you please share the address of the location?

**Comment by jesstelford** [comment]
Thanks for the talk Ajain! Feel free to share the slides here in case others wish to review them. We'll share the recording once it's available.

**Comment by ajainvivek** [comment]
Thanks, @jesstelford Really enjoyed the time in meetup. 

Link to presentation: http://slides.com/ajainvivek/deck-11/fullscreen
Repository Link: https://github.com/ajainvivek/react-memory
