### ISSUE TITLE
React 16's New Features (and what the future of React could be)

### ISSUE THREAD

**Issue by parkroolucas** [reactsydney/talks#66]
## Talk Date
5th February 2018

## Talk Title
What's new in React 16, and what this could mean for the future of React

## Length
10-15 minutes

## Twitter-sized Overview (140 characters)
A tl;dr run-down of all the new features released in "React Fiber", and a look at what the future of React _could_ be in versions 17+.

## Detailed Overview
There was a ton of hype surrounding the then-to-be-released "React Fiber", but now that it is out into the wild, what does that really mean for us developers, what could we be looking to expect from future versions of React, and how can we best prepare for this?

**Comment by jesstelford** [comment]
Love it! Let's lock you in for this Monday, Feb 5th :+1: 

Thanks for stepping up to present this topic :)

**Comment by parkroolucas** [comment]
@jesstelford Thanks! Really excited for my first talk 😃 

Roughly what time will my talk be?

**Comment by jesstelford** [comment]
We'll get you up as second speaker, after the food break. Will most likely be around 7:20, and we'll allocate a max of 15 minutes for you 👍

Am looking forward to it!

**Comment by jesstelford** [comment]
@parkroolucas we'll have to push this talk back to last - around 8pm, is that ok?

**Comment by parkroolucas** [comment]
@jesstelford Thanks to you and the React Sydney community for having me! Is there a link to the recording that you could give me? Thanks 😄

**Comment by jesstelford** [comment]
Thanks for giving the talk Lucas - it was excellent :D 

Our videographer will process and upload the recording when able, then we'll share a link with you :+1:
