### ISSUE TITLE
A Facebook tech stack

### ISSUE THREAD

**Issue by albertstill** [reactsydney/talks#67]
## Talk Date
Monday, March 5, 2018

## Talk Title
A Facebook tech stack

## Length
~20mins

## Twitter-sized Overview (140 characters)
How I built [SplitCommit](https://splitcommit.com/?promoCode=REACTSYDNEY) using open source technology from Facebook, this includes React, Relay Modern and GraphQL.

## Detailed Overview
A complete overview of how I built and hosted [SplitCommit](https://splitcommit.com?promoCode=REACTSYDNEY) using open source libraries from Facebook, this includes React (v16), Relay Modern and GraphQL.js.

[SplitCommit](https://splitcommit.com/?promoCode=REACTSYDNEY) allows groups of friends to save money and easily organise group tours and activities, no individual has to take the risk of covering the whole cost on one card. Attendees can commit to pay their share with their card but no one is charged unless the tipping point is reached, a bit like Kickstarter for social events. We have over 45,000 tours and activities in over 90 countries. Also here is a 10% promo code for React Sydney https://splitcommit.com?promoCode=REACTSYDNEY.

I'll talk about why I think this architecture is the best I've ever worked with (I've worked with a few before - Express(view/controller) + Microservices, Ruby on Rails (MVC) and Symfony (MVC)).

I'll cover dev workflow, databases, CSS, e2e, hosting (Heroku/AWS), SEO, performance monitoring, ip locating and general tips for building a startup internet business. Also how I used a tiny diff [fork](https://www.npmjs.com/package/albert-react-scripts) of Create React App's react-scripts to get what I want but still have the benefits of the ecosystem's best build configuration.

**Comment by jesstelford** [comment]
<3 Great topic! A lot to cover in 20min, let me know if you want more time - we can allocate to to 45min.

**Comment by jesstelford** [comment]
We'll lock you in for Monday, March 5 👍

**Comment by albertstill** [comment]
Cheers. Once I get some slides together I'll give you a better estimate of time.

**Comment by jesstelford** [comment]
We've got a pretty full event for March 5th, so we'll have to have a hard cap of 20minutes for this talk.

**Comment by jesstelford** [comment]
Hey @albertstill confirming you're still able to present for 20 minutes on Monday?

**Comment by albertstill** [comment]
I confirm. Thanks mate
