### ISSUE TITLE
Search. From 6 seconds in LAMP to 100ms in react, go and redis and lessons learned 

### ISSUE THREAD

**Issue by malcolmchetwyn** [reactsydney/talks#68]
## Length
15-30 mins

## Detailed Overview

Below is from a new proptech, fintech platform.

Breaking down the monolith and why microservices can make you slow in small teams.

The major problems we found breaking apart search from LAMP spaghetti into containers and lessons learned.

Why going too micro is bad

How decoupling repos are key to sucessful cross-functional teams and microservice velocity

**Comment by jesstelford** [comment]
Thanks for the submission @malcolmchetwyn.

Given the audience at our events are mostly interested in React / the react ecosystem (graphql, relay, immutable.js, etc), it'd be great if you could make that a prominent portion of the talk.

Our next event is on March 5th.

**Comment by malcolmchetwyn** [comment]
Yep. We can focus on the frontend side :)

**Comment by jesstelford** [comment]
Excellent! The full stack is defintely of interest too, so keep it in, but focusing on frontend will be great.

Can you update the description above, then we can get you listed as a speaker.

We'll lock you in for March 5th :tada:

**Comment by jesstelford** [comment]
We've got a pretty full event for March 5th, so we'll have to have a hard cap of 20minutes for this talk.

**Comment by jesstelford** [comment]
Hey @malcolmchetwyn confirming you're still able to present for 20 minutes on Monday?

**Comment by malcolmchetwyn** [comment]
Sorry mate for the last minute cancellation. I'll need to postpone.

**Comment by jesstelford** [comment]
Not a problem, thanks for letting us know 👍 

Our next event is on May 7th (April is off due to public holiday) - I'll reach back out closer to May to see if you're available then.

**Comment by jesstelford** [comment]
Hey @malcolmchetwyn - are you interested in giving this talk at our June 4th event?

**Comment by jesstelford** [comment]
I'm going to close this issue for now, but please re-open if you want to give the talk at a future event 👍
