### ISSUE TITLE
Low-Code, Citizen Developers and React Freelancing

### ISSUE THREAD

**Issue by holmanist** [reactsydney/talks#69]
**Talk Date**

March 5th 

**Talk Title**

Low-Code, Citizen Developers and React Freelancing

**Length**

~20 minutes

**Twitter-sized Overview (140 characters)**

An overview of our journey building a low-code development platform for connecting business owners to React developers.

**Detailed Overview**

- An overview of how we built our low-code platform [Bappo](https://bappo.com) using node.js, Postgress, Mongo.db, React, React-Native and Redux. See a brief demo.

- The rise of Low-Code and No-Code Development Platforms and the Citizen Developer. To what extent will this trend be a threat or opportunity to React developers?

- How React developers can provide more value to their employers and customers and make more money using low-code tools.

Presentation by Tom Holman and Hernus Carelsen, co-founders of Bappo.

**Comment by jesstelford** [comment]
Hey @tomholman - I like the idea.

While we don't mind folks talking about a product they've built, we prefer the focus to be on the tech and the ecosystem, using the product as a real-world application example. Keep that in mind when structuring your talk, and it will be well received by all :)

I'll schedule you in for the March 5th event - thanks for the submission!

**Comment by jesstelford** [comment]
We've got a pretty full event for March 5th, so we'll have to have a hard cap of 20minutes for this talk.

**Comment by tomholman** [comment]
Great, will do. We'll see you on the 5th of March!

**Comment by jesstelford** [comment]
Hey @tomholman confirming you're still able to present for 20 minutes on Monday?

**Comment by tomholman** [comment]
@jesstelford, yep! Hernus and I are ready to present for 20 minutes

**Comment by jesstelford** [comment]
Looking forward to it :D

**Comment by jesstelford** [comment]
Thanks again for your talk! The recording is now online: https://www.youtube.com/watch?v=uZ0X0lmOFno&feature=youtu.be 🎉
