### ISSUE TITLE
Unit testing in React with Mocha

### ISSUE THREAD

**Issue by yangli1990** [reactsydney/talks#7]
**Talk Date**
Feb 8

**Talk Title**
Unit testing in React with Mocha

**Length**
Somewhere between 40-50mins maybe?

**Twitter-sized Overview (140 characters)**
How to unit tests your React app by using jsdom and mocha in node!

**Detailed Overview**
What unit testing is and what it isn't.
- Difference between unit testing and integration testing
- Why you should use unit tests

How to write components that can be easily unit tested.
- Write pure components whenever possible, use props and avoid state.

Examples of where unit testing can help you or hinder you.
- Give an example of where unit tests can protect you
- Give an example of bad unit tests which can slow down your work

How to set up mocha/jsdom to unit test your React app.
- What mocha is
- What jsdom is
- How to set it up in node
- setup test coverage

Code some unit tests live.
- Using mocha and chai and the expect syntax
- Using react's testutils
- Give examples of how to use spys
- Asynchronous tests

**Comment by jesstelford** [comment]
Testing is an important topic to cover!

Tanya also gave [a talk last time](https://www.youtube.com/watch?v=hWiV--KqYAo) which covered some testing as well as writing some unit tests live.

Could you possibly compare testing with Mocha / React Test Utils with another framework or enzyme / teaspoon? Or maybe even look more into how automated tests can increase your productivity rather than the writing of tests themselves?

**Comment by yangli1990** [comment]
I've never done enzyme/teaspoon but I can compare it to some other frameworks like cucumber or karma.  Yup I can talk about how automated tests can increase productivity. And maybe even explore the new asynchronous testing framework [AVA](https://github.com/sindresorhus/ava)

**Comment by martin-jujou-sirca** [comment]
Maybe also discuss the issues with Jest (advised framework by facebook) - I converted from Jest to mocha in my projects for a number of reasons and there is no way ill go back !

**Comment by jesstelford** [comment]
@yangli1990 Let's save your talk for the next meetup (in a month). That'll give you some time to cover off some of the other points, giving a more holistic view of the testing ecosystem at that point.

**Comment by jesstelford** [comment]
Hey @yangli1990 We've just announced our next meetup on March 7th ([details](http://www.meetup.com/React-Sydney/events/229174524/)) - would you like to give this talk then?

It'd be great to see some things covered such as Enzyme and other testing tools too :)

**Comment by yangli1990** [comment]
Yeah I'd love to give a talk, I will look into putting Enzyme and other testing tools in this too! Thanks

**Comment by JedWatson** [comment]
Excellent, looking forward to it!

**Comment by jesstelford** [comment]
Here's the video from React.js Conf on Enzyme that folks have been talking about: [React.js Conf 2016 - Lightning Talks - Leland Richardson](https://www.youtube.com/watch?v=V5N0Ukb8LGg&list=PLb0IAmt7-GS0M8Q95RIc2lOM6nc77q1IY&index=26)

**Comment by yangli1990** [comment]
Sweet thanks

**Comment by yangli1990** [comment]
@jesstelford has the meetup changed to Tuesday? I won't be able to make Tuesday

**Comment by yangli1990** [comment]
Actually I could maybe make it, I just need to leave by 7.30

**Comment by jesstelford** [comment]
We've had to bump the date of the meetup again - it's now Monday 14th March, are you able to talk then?

If not, no  worries; we can schedule you in again in the future :)

**Comment by yangli1990** [comment]
Hey @jesstelford I'm not sure If I can make it, lets reschedule my talk.

**Comment by jesstelford** [comment]
Not a problem :)

Thanks for submitting the proposal - I'm really looking forward to hearing the talk when we can finally get it in!

**Comment by jesstelford** [comment]
@yangli1990 How are you for April 4th? We'd love to get your talk in the next meetup :)

**Comment by yangli1990** [comment]
Hey Jess, sure I'd love to.

**Comment by jesstelford** [comment]
Excellent stuff :D

**Comment by jesstelford** [comment]
@yangli1990 We have your talk scheduled up first, at 6:30. How long do you think it'll go for (excluding any Q&A time)? Ideally we'd like to keep it no longer than 40 minutes.

**Comment by jesstelford** [comment]
@yangli1990 Totally with the wait for your talk - thanks so much for giving it :D

Do you mind if we upload the recording of your talk to YouTube? If so; any links or resources to add to the description?

Also, do you mind sharing your slides here?

**Comment by yangli1990** [comment]
Pleasure was all mine, thank you guys for giving me to opportunity to talk.

I would love for you to upload it!
Heres the source code repo to the demo https://github.com/yangli1990/react-mocha-jsdom-unit-testing

[ReactMeetup1.pdf](https://github.com/reactsydney/talks/files/202439/ReactMeetup1.pdf)
