### ISSUE TITLE
Intro to ClojureScript

### ISSUE THREAD

**Issue by fdserr** [reactsydney/talks#70]
## Talk Date

March 5th, 2018

## Talk Title

Intro to ClojureScript

## Length

30-45mn

## Twitter-sized Overview (140 characters)

François leads the Digital Technology team at PALO IT; his teams deliver production grade ClojureScript applications in the banking and insurance sectors, following a lean, collaborative development process. He’ll introduce key concepts and demonstrate how live coding with ClojureScript permits the delivery of innovative applications against very tight timelines.

## Detailed Overview

Clojure, the modern LISP for the JVM, had its 10th birthday last year. PALO IT's developers love it: functional programming with immutable values enables teams to deliver faster, with much less code, and less bugs. Meanwhile, ClojureScript (Clojure for JavaScript) has led the way to a new web programming experience: interactive development, aka. live coding. François leads the Digital Technology team at PALO IT; his teams deliver production grade ClojureScript applications in the banking and insurance sectors, following a lean, collaborative development process. He’ll introduce key concepts and demonstrate how live coding with ClojureScript permits the delivery of innovative applications against very tight timelines.

Takeaways:
1. What is essentially  needed to get started with ClojureScript (much less than you’ve been told!).
2. How can interactive development / live coding drastically improve productivity and quality.
3. How easy it is to implement modern front-end architecture blueprints: reactive UI, flux architecture, normalised local store, ... 
4. Next steps: how to develop and test distributed reactive applications in the browser, and port them to production clusters and databases.

**Comment by jesstelford** [comment]
Hey @fdserr, you're confirmed for March 5th! (Apologies for the delay).

We'll have to cap the talk at 30 minutes, we've got a full event :)
