### ISSUE TITLE
Real life React deployments

### ISSUE THREAD

**Issue by evanderkoogh** [reactsydney/talks#73]
## Talk Date 

May 7th

## Talk Title

Real life React Deployments

## Length

~30 min

## Twitter-sized Overview (140 characters)

See how Linc does continuous deployment of React applications with Server-Side Rendering and code-splitting.

## Detailed Overview

The simple way to host a React application is to put it on a static hosting service like S3, Netlify or Surge. But your application isn't a web page, right?

One of the challenges we face when doing more advanced deployments is building for different environments (development, testing, staging, and production for example).
And the holy grail of hosting React applications is the combination of both and Server-Side Rendering (send a rendered page instead of just JS for both SEO & other crawlers and decrease Time to First Paint ) and code splitting (sending only the javascript required for the current page to the client to speed up Time to Interactive)
^^^

**Comment by jesstelford** [comment]
If you're in town, would love to have you present how Linc does those fancy React deployments! Are you still available for May 7th?

**Comment by evanderkoogh** [comment]
Yup.. more than up for it!

**Comment by jesstelford** [comment]
Hey Erwin, checking in - anything I can help with to get you prepared for the event on Monday?

**Comment by jesstelford** [comment]
It'd be great to get a detailed overview filled out above, so when folks are browsing here from the meetup page they can get a good feel for what to expect 👍

**Comment by evanderkoogh** [comment]
Hey man.. I will get around to that today :)

**Comment by jesstelford** [comment]
Love it! 🎉

**Comment by jesstelford** [comment]
This is going to be great! We'll have you up as the second speaker for tonight, most likely after the food break, so everyone will energized and ready to listen :)

**Comment by jesstelford** [comment]
You can now see the recording of this talk on YouTube: https://www.youtube.com/watch?v=8JSKf_N3hPk
