### ISSUE TITLE
Creating Suspense in React 16.2

### ISSUE THREAD

**Issue by petegleeson** [reactsydney/talks#74]
## Talk Date
7th of May 2018

## Talk Title
Creating Suspense in React 16.2

## Length
15-20 mins

## Twitter-sized Overview (140 characters)
Sharing my attempt to create React's newly proposed "Suspense" feature in 16.2 

## Detailed Overview
"Suspense" is a proposed React feature that promises a convenient way of handling all things data fetching related. In an effort to understand how this feature works, I had a crack at implementing it in React 16.2. I would like to share my understanding of what Suspense is, how it works and why it cannot be mimicked in React 16.2.

I wrote about the full details (spoiler alert) here https://medium.com/@pete_gleeson/creating-suspense-in-react-16-2-dcf4cb1a683f 

Thanks!

**Comment by jesstelford** [comment]
Oooh, sounds very interesting! I really enjoy talks walking through exploring a feature and problem space.

Are you still available to give this talk at our May 7th event?

**Comment by petegleeson** [comment]
Yep! That sounds great to me

**Comment by jesstelford** [comment]
Hey Pete, checking in - anything I can help with to get you prepared for the event on Monday?

**Comment by petegleeson** [comment]
Hi Jess, it's all shaping up well from my side. Will I be just plugging my laptop in to present?

**Comment by jesstelford** [comment]
Great to hear! Yep, just plug your laptop into the lecturn, and good to go! More details on the setup here: https://github.com/reactsydney/talks#things-to-think-about

Let me know if you've got any other questions - am happy to help :)

**Comment by jesstelford** [comment]
We've got you up first tonight! Your story is perfect to kick off the evening :) Looking forward to it 👍

**Comment by jesstelford** [comment]
You can now see the recording of this talk on Youtube: https://www.youtube.com/watch?v=DsTsZ6cgPtw
