### ISSUE TITLE
React.Portal: the good, the bad and the ugly

### ISSUE THREAD

**Issue by alexreardon** [reactsydney/talks#75]
## Talk Date

Whenever. May? June? I am fairly flexible

## Talk Title

React.Portal: the good, the bad and the ugly

## Length

20m

## Twitter-sized Overview (140 characters)

React 16 has a first class portal implementation. But wait, what's a portal? In this talk I will go over what portals are on the web and what problems they solve. I will also take a look at `React.Portal` what it does well as well as the things to watch out for.

**Comment by jesstelford** [comment]
Great feature to talk about!

Looks like May 7th might be full (unless anyone pulls out), so can we pencil you in for June 4th?

**Comment by alexreardon** [comment]
Should be good

**Comment by alexreardon** [comment]
I just put it in my calendar 🎉

**Comment by jesstelford** [comment]
Yo @alexreardon, still good for June 4th? Looking forward to this talk 👍

**Comment by alexreardon** [comment]
Yep!!
