### ISSUE TITLE
Prototyping with codesandbox (and codesandboxer)

### ISSUE THREAD

**Issue by Noviny** [reactsydney/talks#76]
## Talk Date

Next meetup with an open talk

## Talk Title

Prototyping with codesandbox (and codesandboxer)

## Length

10 - 20 minutes

## Twitter-sized Overview (140 characters)

First let's talk about what codesandbox is, and then let's talk about how codesandboxer extends the experience for prototyping.

## Detailed Overview

At work I work an a design system. We have been having great success for a while using codesandboxer as a way to collaborate with consumers in both moving forward with both new features and bug fixes. I want to first talk about what codesandbox is, and how it has been helping us, and then dive into how we have been using it, including looking at an open source project we have made to extend how codesandbox works to make this workflow even easier to maintain.

**Comment by jesstelford** [comment]
❤️ it! Our next event is June 4th - are you able to give this talk then?

**Comment by Noviny** [comment]
Definitely.
