### ISSUE TITLE
React For Game Development

### ISSUE THREAD

**Issue by rohan-deshpande** [reactsydney/talks#77]
## Talk Date

2018-06-04

## Talk Title

React For Game Development

## Length

20 - 30 mins

## Twitter-sized Overview (140 characters)

How React and React-like thinking can be used in game development and the pros and cons for using React to make a game.

## Detailed Overview

During my travels as a wannabe indie game developer [building my own old school RPG engine](http://projectgoldscript.com) in React and Three JS, I've continually noticed a lot of interest around using React for game development. 
This talk will aim to impart the knowledge I've gained about this topic in the hope of answering some of the most common questions I have come across in this fairly niche area of software development.

The talk will focus on 

* The key differences between game development and web development and how React or React-like thinking can help bridge this gap 
* The differences between functional and object oriented programming and why this is important for game development 
* The arguments for and against using React for game development 
* Examples on how myself and others are using React for game development

**Comment by jesstelford** [comment]
As an ex-game dev in a previous life, and now full-time react script kiddy, this talk sounds _amazing_ to me!

Locking you in for the next event on June 4th 🎉

**Comment by rohan-deshpande** [comment]
Wow cool! Thanks man, looking forward to it!

**Comment by rohan-deshpande** [comment]
Hey man, quick question are the talks recorded?

**Comment by rohan-deshpande** [comment]
Hey mate, have gotten quite sick, not confident I will be better by Monday :( 

Can we postpone to next month? Would still love to do this talk and it's mostly prepared now. Really hope you can have someone else to fill in, apologies!!!!

**Comment by rohan-deshpande** [comment]
Hey mate, have gotten quite sick, not confident I will be better by Monday :(

Can we postpone to next month? Would still love to do this talk and it's prepared now. Really hope you can have someone else to fill in, apologies!!!!

**Comment by jesstelford** [comment]
_Continuing the discussion from Twitter..._

Not a problem mate, it happens! Let me know if you're feeling better by Monday and we'll slot you back in :)

**Comment by jesstelford** [comment]
Hey @rohan-deshpande, are you available for the July 2nd event (this monday)?

**Comment by rohan-deshpande** [comment]
Yep let's do it! I `Promise` I won't get sick this time.

**Comment by hh8888** [comment]
@rohan-deshpande, I'm a game developer and interested in this, but I miss today's talk. May I have the PPT？Thank you.

**Comment by rohan-deshpande** [comment]
@hh8888 I’ve got some ok video as well as the slides so I’m going to try to upload them soon, gimme a week or so.

**Comment by jesstelford** [comment]
Great talk @rohan-deshpande!

Share the video link here once you've got it uploaded :)

**Comment by rohan-deshpande** [comment]
Video and slides are up, you can check them out [here](http://www.projectgoldscript.com/talks/react-sydney-react-game-development/). I've just exported the slides from keynote as HTML, it's kind of crappy but it works (sort of).
