### ISSUE TITLE
Testing React + GraphQL like a boss

### ISSUE THREAD

**Issue by kaievns** [reactsydney/talks#78]
## Talk Date
Anytime mate, any time

## Talk Title
Testing React + GraphQL like a boss

## Length
the usual, 20 mins + questions

## Twitter-sized Overview (140 characters)
there is a reason why in all the media frenzy about react apollo, you haven't seen a single example how to test it. because it's hard. the good news, we've built something to make it better

## Detailed Overview
For the past 6 months were transitioning towards graphql everything at Shortlyster. Once subject we had run into consistently is how do you test react-apollo apps? The official testing policy is almost non-existent and doesn't offer much beside randomly generated data stubs.

So, i've built this project called [graphql-mock](https://github.com/MadRabbit/graphql-mock) that allows to test react apollo projects in a predictable and civilized way. We've been quite happy using it in the last few months, and so I thought it might be a good idea to share it with the reset of the community.

Also, while we're at it, why don't we turn this into a dazzling life-hacking TDD show?

**Comment by jesstelford** [comment]
A very practical library! Will be great to hear more about it.

I'm pending one thing for our July event, so I'll leave this as Unconfirmed until I have a certain available date (either July 2nd, or August 6th).

**Comment by jesstelford** [comment]
Hey @MadRabbit are you available to give this talk at our July 2nd event (this monday)?

**Comment by kaievns** [comment]
Hey Jess, abshrolutely!

**Comment by jesstelford** [comment]
Excellent, I've locked you in :)

**Comment by kaievns** [comment]
sweet! see you on monday then :)

**Comment by kaievns** [comment]
Hey Jess,

Is there any chance we’d have a headset or a mic stand tonight? I’m going to be life hacking and will need my hands free

**Comment by jesstelford** [comment]
We have a lapel mic (clips onto your shirt), and if that doesn't work, we have a human mic stand (I can hold the mic for you) 👍

**Comment by kaievns** [comment]
awesome, thank you!

**Comment by jesstelford** [comment]
Great talk mate! Really great to see the audience interest in the topic, even though it ran late into the night 🎉

Thank you so much!

**Comment by kaievns** [comment]
No drama at all mate! Thank you for the opportunity!

btw: i've published code from the talk over here https://github.com/MadRabbit/react-sydney-07-2018
