### ISSUE TITLE
React Router and friends

### ISSUE THREAD

**Issue by mrm007** [reactsydney/talks#8]
**Talk Date**
Mar 8

**Talk Title**
React Router and friends

**Length**
30-40mins + questions

**Twitter-sized Overview (140 characters)**
`react-router`, `redux-router`, `redux-simple-router`, `react-router-redux` and other variations. JavaScript fatigue, what?

**Detailed Overview**
- What is React Router?
- Some history on 0.x, 1.x
  - integrating with Redux
  - `redux-router`, `redux-simple-router` or `react-router-redux`
- What's new in 2.x
  - upgrade path
  - integrating with Redux
- Dynamic routing
- Transitions and confirming navigation
- How do I use it in a universal/isomorphic app?
- Conclusions

**Comment by tylerevans** [comment]
+1!

**Comment by blu35ky** [comment]
+1 :+1:

**Comment by rcmlee99** [comment]
+1

**Comment by jgrancher** [comment]
:+1:

**Comment by jesstelford** [comment]
Excellent talk proposal! Let's definitely fit this one in :)

@mrm007 On a related note: The date has been changed to Monday 14th March - are you still able to give the talk then?

**Comment by mrm007** [comment]
@jesstelford not a problem, this gives me more time to polish the talk :)

**Comment by jesstelford** [comment]
Awesome stuff, thanks for being flexible :)

**Comment by jesstelford** [comment]
@mrm007 Thanks so much for giving a talk last night! Do you mind sharing a link to the slides here?
