### ISSUE TITLE
Going native

### ISSUE THREAD

**Issue by iamhitarth** [reactsydney/talks#80]
## Talk Date
04-06-2018 or July

## Talk Title
Going (from React to React) Native
![](http://s.quickmeme.com/img/22/22096014c151e2e3149d44c192d72b2c6ca121a47676807aef1ff5a72fc6ad4a.jpg)

## Length
10-20 mins

## Twitter-sized Overview (140 characters)
Learn once, write anywhere. That's the React philosophy but is that really true?
![](https://media.giphy.com/media/a5viI92PAF89q/giphy.gif)

## Detailed Overview
In September 2017, having worked with React for a little while, I got the opportunity to work on the Afterpay app using React Native (with no prior native development experience)  and test out the React philosophy of learn once, write anywhere. 
Two months into that contract, I got another chance to test that philosophy when an EduTech company needed their React engineers to be led into the React Native world. 
In this talk, I will go through my experiences of moving from React to React Native and along the way point out specifics to watch out for/take note of if/when you go through that transition yourself.

**Comment by jesstelford** [comment]
Very interesting! I'm keen to hear how the transition went :D 

Let's put you in for the July 2nd event, we're a little too close to the June event now.

**Comment by iamhitarth** [comment]
Thanks @jesstelford - keen to present! 

Can we move this to August though? As I might be travelling around the 2nd July.

**Comment by jesstelford** [comment]
Hey @iamhitarth no worries - August works well.

We've still got space on 2nd July if you're around?

**Comment by jesstelford** [comment]
Hey @iamhitarth, are you still happy to give this talk at the August 6th event?

**Comment by iamhitarth** [comment]
Yup good to go for 6th Aug @jesstelford 

Apologies for the delayed response!

**Comment by jesstelford** [comment]
Hey @iamhitarth - How's prep going for the event on Monday? Anything I can help with?

**Comment by iamhitarth** [comment]
Yup getting there! 

Will it be possible to have my talk scheduled in the first half?

**Comment by jesstelford** [comment]
🎉 Great to hear!

We can have you up first if you like?

**Comment by jesstelford** [comment]
Great talk! If you've got any slides or other resources to share, feel free to post them here.
