### ISSUE TITLE
Convert components between function and class

### ISSUE THREAD

**Issue by sungwoncho** [reactsydney/talks#81]
## Talk Date
As availability permits

## Talk Title
Instantly convert React components between function and class

## Length
20 - 30 min

## Twitter-sized Overview (140 characters)
compconv instantly converts your React components between functional and class components by walking the JSX tree.

## Detailed Overview

We often change React component between functional and classical ones. For instance, sometimes a component extending `React.Component` no longer requires any states or methods. In that case, we rewrite it as a pure function, and vice-versa.

However the process is time consuming and tedious, and therefore it gets in the way of refactoring. compconv automates the process.

https://github.com/sungwoncho/compconv

**Comment by jesstelford** [comment]
Ooh, I like the tool! Very nice!

Are you available for the August 6th event?

**Comment by sungwoncho** [comment]
How do you feel about July?

**Comment by sungwoncho** [comment]
Hi @jesstelford. Could you lock this in for the August meetup?

**Comment by sungwoncho** [comment]
@jesstelford you must be busy. when you get some downtime, could you confirm this talk for August?

**Comment by jesstelford** [comment]
Sorry for the delayed reply @sungwoncho - let's lock you in for the August 6th event! 🎉

**Comment by sungwoncho** [comment]
Thanks. See you there.

**Comment by jesstelford** [comment]
Hey @sungwoncho - How's prep going for the event on Monday? Anything I can help with?

**Comment by sungwoncho** [comment]
Hi @jesstelford, I am good to go on Monday. Thanks for checking in

**Comment by jesstelford** [comment]
Great talk! If you've got any slides or other resources to share, feel free to post them here.

**Comment by sungwoncho** [comment]
Thanks.

* slides: https://sungwoncho.github.io/presentations/20180806-compconv.html
* repo: https://github.com/sungwoncho/compconv
