### ISSUE TITLE
Patterns and Antipatterns when testing react applications with Jest + Enzyme

### ISSUE THREAD

**Issue by iamsuganthi** [reactsydney/talks#82]
## Talk Date
August 6th

## Talk Title
Patterns and Antipatterns when testing react applications with Jest + Enzyme

## Length
20 mins + Q&A

## Twitter-sized Overview (140 characters)
There are some widely used patterns when testing React applications. I would like to discuss how some of these patterns are actually anti-patterns.

## Detailed Overview
Good unit tests are those which test behavior rather than verifying the implementation. If our tests aren't doing exactly what the user will do, then how do we really know that things will work when users interact with our apps. 

I would like to discuss with examples, some patterns and anti-patterns in testing react applications with jest and enzyme. 

Github: https://github.com/enthudrives/testing_with_jest_enzyme

**Comment by jesstelford** [comment]
Oooh, this sounds like exactly what I need right now! And I'm 100% sure the audience will get a lot out of this - let's lock it in for the August 6th event. Thanks!

**Comment by iamsuganthi** [comment]
@jesstelford Sounds great. Looking forward to it. :)

**Comment by jesstelford** [comment]
Hey @enthudrives - How's prep going for the event on Monday? Anything I can help with?

**Comment by jesstelford** [comment]
We'll have you up second tomorrow night - around 7:15 or 7:30 👍

**Comment by iamsuganthi** [comment]
@jesstelford I will be there around 6. All set for 7:15 👍 
Thanks for the reminder!

**Comment by jesstelford** [comment]
Awesome, see you soon 👍

**Comment by jesstelford** [comment]
Great talk! If you've got any slides or other resources to share, feel free to post them here.
