### ISSUE TITLE
From CLI to GUI

### ISSUE THREAD

**Issue by Raathigesh** [reactsydney/talks#83]
## Talk Date
6th August or any other date

## Talk Title
From CLI to GUI

## Length
20 Minutes

## Twitter-sized Overview (140 characters)
Most dev tools come with a CLI built in, but what if they come with a GUI as well?

## Detailed Overview
Recently the front-end community started to focus on building GUIs on top of existing CLI tools. [Guppy ](https://github.com/joshwcomeau/guppy) is an excellent example of this. I myself built a GUI for jest called [majestic](https://github.com/Raathigesh/majestic/) a while ago and rewriting it to make it more functional.

In this talk I would like to make a case for why there should be more GUIs for dev tools, introduce the imrpoved majestic and talk about the tech we could use to build these tools.

**Comment by jesstelford** [comment]
I'm a big fan of this movement 👍

I'm pending confirmation of a couple other talks for August, so at this point we'll schedule you for a future event, but I'll let you know if anything changes 👍

**Comment by jesstelford** [comment]
We've filled up the August event for now, so I'll leave this as date unconfirmed until next month. 👍

**Comment by Raathigesh** [comment]
No worries, Jess 👍

**Comment by jesstelford** [comment]
Hey @Raathigesh - we'd love to have you give this talk at the September event on Monday, does that work for you?

**Comment by Raathigesh** [comment]
Hey Jess, That works for me 👍 🎉

**Comment by jesstelford** [comment]
Wonderful - see you there :)

We'll have you up first for the evening.

**Comment by Raathigesh** [comment]
Awesome 👍
