### ISSUE TITLE
Into the sausage factory 🌭

### ISSUE THREAD

**Issue by alexreardon** [reactsydney/talks#84]
## Talk Date

October 2018

## Talk Title

Into the sausage factory

## Length

~20-40m

## Twitter-sized Overview (140 characters)

We recently added a feature to `react-beautiful-dnd` which fundamentally changed how the library hangs together. Come on a journey of discovery, agony, hopelessness and elation as we explore what it took to allow dynamic changes to a list during a drag

**Comment by jesstelford** [comment]
Haha, great title!

We won't be having an event in October (public holiday), but the next one after is November 5th. Alternatively, we may have space in the September 3rd event.

**Comment by jesstelford** [comment]
You keen to give this talk on Monday for our September event?

**Comment by alexreardon** [comment]
I won’t be able to Jess. The work is not done yet 😊

**Comment by jesstelford** [comment]
Haha, not a problem - let's keep you penciled in for the November event 👍
