### ISSUE TITLE
react { css-in-js: overflow }

### ISSUE THREAD

**Issue by elektronik2k5** [reactsydney/talks#85]
## Talk Date
TBD - I'm arriving to Australia in mid September and plan to stay for at least three months. I understand there's no event in October, so perhaps November?

## Talk Title
react { css-in-js: overflow }

## Length
30-40 minutes

## Twitter-sized Overview (140 characters)
CSS-in-JS is taking the world by storm! This is an overview of what's possible today in the React and styling landscape.

## Detailed Overview
While JS and HTML have progressed incredibly in recent years, CSS is the last bastion of old-school web development which we all love to hate. CSS-in-JS is the latest attempt at solving this hard problem. If it succeeds, CSS-in-JS will fast-forward CSS into the modern era. Moreover, it will revolutionize how we compose, maintain, share and optimize styling across the modern web, native apps and collaborate with designers and product people. I will present an overview of the history, evolution, challenges, current solutions and benefits in this exciting landscape!

Slides: https://slides.com/elektronik/react-css-in-js/
Video of this talk: https://youtu.be/8qnK0c_NQmE?t=26s

Note that I'll update the talk content to reflect the latest developments in this highly dynamic landscape:
- Add https://stylable.io/
- Add https://github.com/vincentriemer/react-native-dom
- Remove duplicate/obsolete packages from overview

I'm also open to feedback and suggestions :)

**Comment by jesstelford** [comment]
<3 it! I'll put you in as a tentative November.

We also have a related event in October which this talk may be suitable for - we're still putting together the structure, but if you'd like to [submit a proposal here](https://codeheartdesign.com/), we'll add it to the list!

**Comment by elektronik2k5** [comment]
Thanks @jesstelford! I also submitted to the Code❤️Design Conf.
I'll update here the details of my travel plans and availability, as they solidify.

**Comment by elektronik2k5** [comment]
I'm sad to say that me and my spouse's visa application was denied. :disappointed: 
Apparently, long term travel makes immigration officials suspect we'll want to stay in Australia longer than the visa we applied for. Never mind that the two are actually _contradictory_...

Consequently, I'm forced to cancel my participation.
I apologize for the inconvenience, and am grateful for the opportunity.

Hopefully, I'll get to Australia some day in the future, when government bureaucrats are a bit less suspicious of digital nomads.

Again, sorry for the trouble!
