### ISSUE TITLE
Build Teams, Maintain Culture While Moving Fast

### ISSUE THREAD

**Issue by ttsui** [reactsydney/talks#87]
## Talk Date
September React Meetup

## Talk Title
Build Teams, Maintain Culture While Moving Fast

## Length
60 mins

## Twitter-sized Overview (140 characters)
Panel discussion on how to build teams and maintain culture while sustaining a high development velocity.

## Detailed Overview
Panelist from the following companies will discuss how they grew their teams and maintain team culture while sustaining a high development velocity.

#### Moderator
[Andrew Donald](https://www.linkedin.com/in/andrewdonald/)  - Head of Talent at AirTree Ventures

#### Panelist
[Claire Tran](https://www.linkedin.com/in/claire-tran-3812114/) - Technical Lead at Expert360
[Ted Tencza](https://www.linkedin.com/in/ttencza/) - Head Of Engineering at Prospa
[Tony Tsui](https://www.linkedin.com/in/tony-tsui-8906494/) - Senior Software Engineer at GlamCorner

**Comment by jesstelford** [comment]
Love it! This is going to be a great panel 🎉 

Locked in for the September 3rd meetup.

**Comment by jesstelford** [comment]
Hey folks, here's the schedule for Monday's event:

- 18:00: Doors open (come introduce yourself to me - find my dreadlocks 😉)
- 18:30: Intros & state of the ecosystem update
- 18:40: Our first talk: [From CLI to GUI](https://github.com/reactsydney/talks/issues/83)
- 19:00: Break for Pizza & drinks (and networking)
- 19:30: Sponsor shout outs
- **19:35: Your panel**
- 20:35: Wrap up & thanks
- 21:00: Vacate the venue

_(We're not super strict on the schedule, so the above times are more of a guide than anything else)_

The event is listed here: https://www.meetup.com/React-Sydney/events/253660818/

**Comment by pro-ttencza** [comment]
The slides I talked about during the panel discussion can be found at https://www.slideshare.net/darthted/

The video of Remote Teams can be seen at https://www.youtube.com/watch?v=6Rd5HqTo6-4
