### ISSUE TITLE
Using Webpack at Scale

### ISSUE THREAD

**Issue by joshhunt** [reactsydney/talks#9]
## Talk Date
Mar 14

## Talk Title
Using Webpack At Scale

## Length
10-15mins + questions

## Twitter-sized Overview (140 characters)
Webpack can be tricky, especialy as your project grows. I'll go over we're taking advantage of Webpack, and how we managed it's pains. 

## Detailed Overview

* Extremely brief overview of Webpack
* Features useful in larger code bases
* Asset manifests
* Code splitting
* Universal JS - Webpack for server side code
* How to run tests quickly
* Managing and creating different configs without dying

**Comment by jesstelford** [comment]
Great proposal! And nice and short too - let's go ahead with this talk on March 14th :)

**Comment by JedWatson** [comment]
Can't wait to hear what you've got to say about this @joshhunt!

**Comment by samelliott89** [comment]
Pumped!

**Comment by jesstelford** [comment]
@joshhunt We've got your talk scheduled in at 7:00 for 15 minutes (including questions, but we can extend that a bit if there are a lot of Q's).

When you get there tonight, come find myself or Jed and we can help you get setup :)

**Comment by jesstelford** [comment]
Excellent talk @joshhunt - thanks so much! Do you mind sharing a link to the slides here?

**Comment by joshhunt** [comment]
No worries @jesstelford - it was a lot of fun.

Slides up https://speakerdeck.com/joshhunt/using-webpack-at-scale
