### ISSUE TITLE
React 16.6: Suspend your disbelief

### ISSUE THREAD

**Issue by gwyneplaine** [reactsydney/talks#90]
## Talk Date
Nov 5th

## Talk Title
React 16.6: Suspend your disbelief

## Length
20

## Twitter-sized Overview (140 characters)
A brief overview and demo of 16.6 and why it's neato burrito  

## Detailed Overview
TBA

**Comment by incessantmeraki** [comment]
@gwyneplaine If possible include the stuff about React Hooks as well which was introduced in React 16.7

**Comment by nkbt** [comment]
I reckon Hooks worth a separate talk...

**Comment by jesstelford** [comment]
This is a great talk for the current state of things! Will be great to see another talk on the future of React with hooks, etc.

Let's lock you in for November 5th 👍
