### ISSUE TITLE
React hooks

### ISSUE THREAD

**Issue by pksjce** [reactsydney/talks#91]
## Talk Date
? Not sure ?

## Talk Title
About React hooks (Cooler title TBD)

## Length
10-20 mins

## Twitter-sized Overview (140 characters)
All about react-hooks. Why and how? My experience with [react-powerhooks
](https://github.com/kalcifer/react-powerhooks)

## Detailed Overview
[react-powerhooks](https://github.com/kalcifer/react-powerhooks)

**Comment by jesstelford** [comment]
This would be a great talk!

Are you available to give it at this Monday's event (November 5th)? It will pair perfectly with https://github.com/reactsydney/talks/issues/90

**Comment by jesstelford** [comment]
Confirmed offline 👍
