### ISSUE TITLE
How to write 90% clean code with React Hooks

### ISSUE THREAD

**Issue by singhArmani** [reactsydney/talks#92]
## Talk Date
3 Dec, 2018

## Talk Title
How to write 90% clean code with React Hooks

## Length
45-60 mins

## Twitter-sized Overview (140 characters)

Current problems with reusing code logic in React, and how can we resolve these problems using new React Hooks API.

## Detailed Overview
As of now, it's not very easy to reuse code logic across different React components. We have a few patterns like HOC and render props which comes to rescue but creates a wrapper hell problem. Class components are the only way to create stateful components and require lots of boiler plate code to abstract a single logic. Creation of side effects and then clearing up the resources is spread across different life cycle hooks thus giving us 'No single responsibility' problem. 

With new React hooks proposal, we can look into resolving these issues in a much better way. And by adopting these new hooks, we can end up writing 90% clean code.

Talk will include some of the slides, follow up with some live coding demo.

**Comment by jesstelford** [comment]
Hey @singhArmani - This sounds like a great talk! I know it's short notice, but we'd love to have you present it at our event on Monday night if possible 👍

**Comment by singhArmani** [comment]
Hi Jess,

Thanks for accepting my talk. I will be looking forward to present it on Monday night. 😀


Regards,

Aman

On Dec 1, 2018 7:35 AM, Jess Telford <notifications@github.com> wrote:

Hey @singhArmani<https://github.com/singhArmani> - This sounds like a great talk! I know it's short notice, but we'd love to have you present it at our event on Monday night if possible 👍
