### ISSUE TITLE
Testing variations of the same test

### ISSUE THREAD

**Issue by ajaymathur** [reactsydney/talks#94]
## Talk Date
Don't mind

## Talk Title
jest-in-case

## Length
5-8 mins lightning talk

## Twitter-sized Overview (140 characters)
Test variations of the same test, especially useful when testing components

## Detailed Overview
This is talk is about a library [jest-in-case](https://github.com/atlassian/jest-in-case). This enables you to test variations of the same test easily.

**Comment by jesstelford** [comment]
@ajaymathur I love this idea for a lightning talk!

We could fit you to our April 1st event if you're available?
