### ISSUE TITLE
Domain Group migration from SASS -> CSS-in-JS

### ISSUE THREAD

**Issue by jooj123** [reactsydney/talks#96]
## Talk Date

TBC 
~ April because i need to create the content still

## Talk Title

Domains CSS in JS Journey

## Length

20-30 mins ?

## Twitter-sized Overview (140 characters)

fe-co-no-sass 🙅

## Detailed Overview

Talk about Domain Group migration from SASS -> CSS in JS.

I plan to go over:

- The motivations for moving to CSS in JS
- How we chose which library
- Migration Guide 
- Challenges along the way
- What the future holds

**Comment by jesstelford** [comment]
🎉 Thanks for the talk submission, it looks great (and I'm very keen to hear how Domain has progressed)!

To make managing the event easier, we've decided to use a different tool for CFPs; [Cete](https://cete.io)

Do you mind please resubmitting your talk via [the `React Sydney` CFP form on Cete](https://beta.cete.io/react-sydney/cfp/new) 🙏
