### ISSUE TITLE
Building a browser extension with React and Webpack

### ISSUE THREAD

**Issue by fwouts** [reactsydney/talks#97]
## Talk Date
June 2019

## Talk Title
Building a browser extension with React and Webpack

## Length
Unsure. Probably around 45 minutes to 1 hour.

## Twitter-sized Overview (140 characters)
Learn how to build a browser extension (Chrome and Firefox) with a complex UI by leveraging React, Webpack and Babel 

## Detailed Overview

Have you ever wanted to build a Chrome or Firefox extension? We'll build a simple web app and transform it into a fully functional browser extension. We'll walk through how to use Webpack and Babel to get the best possible developer experience. No prior knowledge required.

Slides: https://fwouts.github.io/talk-browser-extension

**Comment by fwouts** [comment]
Is this the correct place to propose a talk nowadays?

**Comment by driesg** [comment]
@fwouts I just found this comment: https://github.com/reactsydney/talks/issues/96#issuecomment-465442576

**Comment by fwouts** [comment]
@jesstelford I'm trying to submit my talk at https://beta.cete.io/react-sydney/cfp/new, but the form submission crashed (error 4cbc73bdfdb94e1b9f7ac096474ba2f2). After a couple of minutes it refreshed itself with another crash "NO_STATUS_CODE_FROM_LAMBDA". Let me know if you need help debugging it.

**Comment by jesstelford** [comment]
😱 Oh no! I missed this one, I'm so sorry!

We have a couple bugs with Cete right now, I've just come back here to temporarily accept talks via GitHub again.

This talk looks great for our June event! If you're still available, I'd love to have you :)

**Comment by fwouts** [comment]
Let's do it! I'm in for the June event :) Is it at Domain?

**Comment by jesstelford** [comment]
We have a new venue this month at Atlassian's HQ: 363 George Street

**Comment by jesstelford** [comment]
We'll have you up second on Monday: https://www.meetup.com/React-Sydney/events/261817672/
