### ISSUE TITLE
Elements in motion

### ISSUE THREAD

**Issue by itsdouges** [reactsydney/talks#98]
## Talk Date
July? If needed in June I can try and do something quickly.

## Talk Title
Elements in motion

## Length
30min + questions

## Twitter-sized Overview (140 characters)
History of elements in motion on the web and the introduction of a powerfully simple library to make this easy for everyone.

## Detailed Overview
Tbc - finally stepping up to talk about this properly 😅

**Comment by jesstelford** [comment]
Yes! This will be a great talk. We'd love to have you in our June event (this Monday) if possible <3

**Comment by itsdouges** [comment]
@jesstelford yeahhh i can rangle something up, ok

**Comment by jesstelford** [comment]
We'll have you up first on Monday: https://www.meetup.com/React-Sydney/events/261817672/

Don't forget the new venue (at your office): Level 29, 363 George Street
