### ISSUE TITLE
The History of React-Hot-Loader

### ISSUE THREAD

**Issue by theKashey** [reactsydney/talks#99]
## Talk Date
In a week or two after acceptance to get slides ready.

## Talk Title
The History of React-Hot-Loader

## Length
30min + questions

## Twitter-sized Overview (140 characters)
There are Three Pillars, which emerge simultaneously - Dan, Redux, and Hot-Loader. And this is a story about what happened in the next few years.

## Detailed Overview
A brief explanation about the pros and cons of the technology itself, explanation of how it works, and all the decisions made from version 1 to 5.

**Comment by jesstelford** [comment]
This is a great talk idea! Let's schedule you in for the July 1st event 👍

**Comment by theKashey** [comment]
👍, I'll prepare the slides then

**Comment by theKashey** [comment]
Attaching draft slides (12mb).
[hot-react-sydney.pdf](https://github.com/reactsydney/talks/files/3337607/hot-react-sydney.pdf)

**Comment by jesstelford** [comment]
Thanks for sharing the slides! There are a few code examples which are using smaller font sizes - I'd suggest making them bigger by about 2x (and remove some surrounding code if necessary), otherwise it wont be readable by folks at the back of the room.
